In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook

In [2]:
eth_dfd = pd.read_csv('../Dataset/Binance_ETHUSDT_1h.csv')
eth_dfd

Unix                 Date   Symbol     Open     High      Low  \
0      1672527600000  2022-12-31 23:00:00  ETHUSDT  1196.18  1197.43  1193.60   
1      1672524000000  2022-12-31 22:00:00  ETHUSDT  1200.09  1201.11  1193.08   
2      1672520400000  2022-12-31 21:00:00  ETHUSDT  1202.33  1203.00  1199.83   
3      1672516800000  2022-12-31 20:00:00  ETHUSDT  1202.66  1203.71  1202.30   
4      1672513200000  2022-12-31 19:00:00  ETHUSDT  1199.59  1205.61  1199.42   
...              ...                  ...      ...      ...      ...      ...   
26269  1577851200000  2020-01-01 04:00:00  ETHUSDT   130.21   130.74   130.15   
26270  1577847600000  2020-01-01 03:00:00  ETHUSDT   130.85   130.89   129.94   
26271  1577844000000  2020-01-01 02:00:00  ETHUSDT   130.63   130.98   130.35   
26272  1577840400000  2020-01-01 01:00:00  ETHUSDT   128.87   130.65   128.78   
26273  1577836800000  2020-01-01 00:00:00  ETHUSDT   129.16   129.19   128.68   

         Close   Volume ETH   Volume USDT  tradecount  
0      1196.13   5927.43200  7.086714e+06       11029  
1      1196.19   9549.47930  1.143952e+07       13241  
2      1200.10   3865.48620  4.643401e+06        7913  
3      1202.34   3557.34730  4.278879e+06        7917  
4      1202.65   6435.02040  7.738029e+06        9906  
...        ...          ...           ...         ...  
26269   130.20   3397.90747  4.430067e+05        2264  
26270   130.20   4968.55433  6.473610e+05        2818  
26271   130.85   7603.35623  9.940256e+05        3046  
26272   130.64  11344.65516  1.474278e+06        4885  
26273   128.87   7769.17336  1.000930e+06        2504  

[26274 rows x 10 columns]

In [3]:
df = Preprocessing.feature_selection(eth_dfd)
df

Open     High      Low   Volume USDT    Close
0       129.16   129.19   128.68  1.000930e+06   128.87
1       128.87   130.65   128.78  1.474278e+06   130.64
2       130.63   130.98   130.35  9.940256e+05   130.85
3       130.85   130.89   129.94  6.473610e+05   130.20
4       130.21   130.74   130.15  4.430067e+05   130.20
...        ...      ...      ...           ...      ...
26269  1199.59  1205.61  1199.42  7.738029e+06  1202.65
26270  1202.66  1203.71  1202.30  4.278879e+06  1202.34
26271  1202.33  1203.00  1199.83  4.643401e+06  1200.10
26272  1200.09  1201.11  1193.08  1.143952e+07  1196.19
26273  1196.18  1197.43  1193.60  7.086714e+06  1196.13

[26274 rows x 5 columns]

In [4]:
df_no_dup = Preprocessing.handle_duplicate(df)
df_no_dup

duplicate ok


Open     High      Low   Volume USDT    Close
0       129.16   129.19   128.68  1.000930e+06   128.87
1       128.87   130.65   128.78  1.474278e+06   130.64
2       130.63   130.98   130.35  9.940256e+05   130.85
3       130.85   130.89   129.94  6.473610e+05   130.20
4       130.21   130.74   130.15  4.430067e+05   130.20
...        ...      ...      ...           ...      ...
26269  1199.59  1205.61  1199.42  7.738029e+06  1202.65
26270  1202.66  1203.71  1202.30  4.278879e+06  1202.34
26271  1202.33  1203.00  1199.83  4.643401e+06  1200.10
26272  1200.09  1201.11  1193.08  1.143952e+07  1196.19
26273  1196.18  1197.43  1193.60  7.086714e+06  1196.13

[26274 rows x 5 columns]

In [5]:
miss = Preprocessing.handle_missing_value(df_no_dup)
miss

No missing value


False

In [6]:
x, scaler = Preprocessing.minmax_scale(df_no_dup)
x

array([[0.00687306, 0.00493458, 0.00899058, 0.00085515, 0.00678935],
       [0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
       [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
       ...,
       [0.23278314, 0.23041549, 0.23462933, 0.00396711, 0.23230718],
       [0.2323116 , 0.23001863, 0.23320743, 0.00977339, 0.23148404],
       [0.23148852, 0.22924589, 0.23331697, 0.00605456, 0.2314714 ]])

In [7]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.00687306, 0.00493458, 0.00899058, 0.00085515, 0.00678935],
       [0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
       [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
       ...,
       [0.36569953, 0.36527651, 0.3650033 , 0.03678181, 0.36294049],
       [0.36293557, 0.3619231 , 0.35881859, 0.0818867 , 0.35696376],
       [0.35696347, 0.35758067, 0.3546814 , 0.09563107, 0.35310278]])

In [8]:
test

array([[0.35310067, 0.35162768, 0.34770043, 0.15036013, 0.34664396],
       [0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
       [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
       ...,
       [0.23278314, 0.23041549, 0.23462933, 0.00396711, 0.23230718],
       [0.2323116 , 0.23001863, 0.23320743, 0.00977339, 0.23148404],
       [0.23148852, 0.22924589, 0.23331697, 0.00605456, 0.2314714 ]])

In [9]:
train_X, train_y = Preprocessing.create_dataset(train,5)
test_X, test_y = Preprocessing.create_dataset(test,5)

In [10]:
train_X

array([[[0.00687306, 0.00493458, 0.00899058, 0.00085515, 0.00678935],
        [0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
        [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
        [0.00722882, 0.00529155, 0.009256  , 0.00055308, 0.00706934],
        [0.00709409, 0.00526005, 0.00930024, 0.00037848, 0.00706934]],

       [[0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
        [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
        [0.00722882, 0.00529155, 0.009256  , 0.00055308, 0.00706934],
        [0.00709409, 0.00526005, 0.00930024, 0.00037848, 0.00706934],
        [0.00709199, 0.00520336, 0.00929181, 0.00047243, 0.00709039]],

       [[0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
        [0.00722882, 0.00529155, 0.009256  , 0.00055308, 0.00706934],
        [0.00709409, 0.00526005, 0.00930024, 0.00037848, 0.00706934],
        [0.00709199, 0.00520336, 0.00929181, 0.00047243, 0.00709039],
        [0.00711

In [11]:
train_y

array([0.00709039, 0.00711987, 0.00707776, ..., 0.36294049, 0.35696376,
       0.35310278])

In [12]:
test_X

array([[[0.35310067, 0.35162768, 0.34770043, 0.15036013, 0.34664396],
        [0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
        [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.34708184],
        [0.34708226, 0.34721595, 0.34265955, 0.10696327, 0.34520188]],

       [[0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
        [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.34708184],
        [0.34708226, 0.34721595, 0.34265955, 0.10696327, 0.34520188],
        [0.34520033, 0.35104603, 0.3447787 , 0.10501199, 0.35243332]],

       [[0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.34708184],
        [0.34708226, 0.34721595, 0.34265955, 0.10696327, 0.34520188],
        [0.34520033, 0.35104603, 0.3447787 , 0.10501199, 0.35243332],
        [0.35243

In [13]:
test_y

array([0.35243332, 0.35114703, 0.35150913, ..., 0.23230718, 0.23148404,
       0.2314714 ])

In [14]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(21014, 5, 5) (21014,) (5250, 5, 5) (5250,)


## Model Training

In [15]:
hyperparams = []
batch = [32, 64, 128]
epoch = [100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(32, 100, 50),
 (32, 100, 60),
 (32, 100, 100),
 (64, 100, 50),
 (64, 100, 60),
 (64, 100, 100),
 (128, 100, 50),
 (128, 100, 60),
 (128, 100, 100)]

In [16]:
bilstms = []
models = []
for batch, epoch, neuron in hyperparams:
    model, bilstm = LSTMUnit.train_bilstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    bilstms.append(bilstm)
    models.append(model)

Metal device set to: Apple M1


2023-03-21 09:56:06.334829: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-21 09:56:06.335301: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-03-21 09:56:06.667755: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


Epoch 1/100


2023-03-21 09:56:08.054148: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 09:56:08.231643: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 09:56:08.264737: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 09:56:10.122468: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 09:56:10.138658: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 09:56:18.988715: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 09:56:19.037925: I tensorflow/core/grappler/optimizers/cust

657/657 - 14s - loss: 2.2085e-04 - val_loss: 2.8631e-04 - 14s/epoch - 21ms/step
Epoch 2/100
657/657 - 9s - loss: 2.5279e-04 - val_loss: 2.8620e-04 - 9s/epoch - 13ms/step
Epoch 3/100
657/657 - 9s - loss: 3.5138e-04 - val_loss: 2.1923e-04 - 9s/epoch - 14ms/step
Epoch 4/100
657/657 - 9s - loss: 5.8333e-04 - val_loss: 3.9043e-04 - 9s/epoch - 14ms/step
Epoch 5/100
657/657 - 9s - loss: 7.8875e-04 - val_loss: 8.2832e-04 - 9s/epoch - 14ms/step
Epoch 6/100
657/657 - 9s - loss: 7.3860e-04 - val_loss: 7.0072e-04 - 9s/epoch - 14ms/step
Epoch 7/100
657/657 - 9s - loss: 6.2234e-04 - val_loss: 4.7254e-04 - 9s/epoch - 14ms/step
Epoch 8/100
657/657 - 9s - loss: 5.1490e-04 - val_loss: 2.9889e-04 - 9s/epoch - 14ms/step
Epoch 9/100
657/657 - 9s - loss: 4.3994e-04 - val_loss: 1.9687e-04 - 9s/epoch - 14ms/step
Epoch 10/100
657/657 - 9s - loss: 3.8884e-04 - val_loss: 1.4032e-04 - 9s/epoch - 13ms/step
Epoch 11/100
657/657 - 9s - loss: 3.5191e-04 - val_loss: 1.0922e-04 - 9s/epoch - 13ms/step
Epoch 12/100
657/6

2023-03-21 10:11:10.753250: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:10.919584: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:10.932885: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:11.043339: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:11.063397: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:19.944726: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:20.000193: I tensorflow/core/grappler/optimizers/cust

657/657 - 11s - loss: 1.4723e-04 - val_loss: 3.6804e-04 - 11s/epoch - 17ms/step
Epoch 2/100
657/657 - 9s - loss: 1.8044e-04 - val_loss: 2.7482e-04 - 9s/epoch - 14ms/step
Epoch 3/100
657/657 - 9s - loss: 1.9044e-04 - val_loss: 2.3666e-04 - 9s/epoch - 14ms/step
Epoch 4/100
657/657 - 9s - loss: 2.1233e-04 - val_loss: 2.4672e-04 - 9s/epoch - 14ms/step
Epoch 5/100
657/657 - 9s - loss: 2.8919e-04 - val_loss: 1.9506e-04 - 9s/epoch - 14ms/step
Epoch 6/100
657/657 - 9s - loss: 4.8839e-04 - val_loss: 2.5747e-04 - 9s/epoch - 14ms/step
Epoch 7/100
657/657 - 9s - loss: 7.1453e-04 - val_loss: 7.1563e-04 - 9s/epoch - 14ms/step
Epoch 8/100
657/657 - 9s - loss: 7.0130e-04 - val_loss: 6.7089e-04 - 9s/epoch - 14ms/step
Epoch 9/100
657/657 - 9s - loss: 5.9496e-04 - val_loss: 4.6543e-04 - 9s/epoch - 14ms/step
Epoch 10/100
657/657 - 9s - loss: 4.8794e-04 - val_loss: 3.0168e-04 - 9s/epoch - 14ms/step
Epoch 11/100
657/657 - 9s - loss: 4.1664e-04 - val_loss: 1.9883e-04 - 9s/epoch - 14ms/step
Epoch 12/100
657/6

2023-03-21 10:27:11.828574: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:11.992545: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:12.007145: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:12.255987: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:12.275330: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:21.974108: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:22.041624: I tensorflow/core/grappler/optimizers/cust

657/657 - 13s - loss: 1.6201e-04 - val_loss: 5.1302e-04 - 13s/epoch - 19ms/step
Epoch 2/100
657/657 - 10s - loss: 1.8236e-04 - val_loss: 3.1605e-04 - 10s/epoch - 16ms/step
Epoch 3/100
657/657 - 10s - loss: 1.8740e-04 - val_loss: 3.1573e-04 - 10s/epoch - 16ms/step
Epoch 4/100
657/657 - 10s - loss: 2.1248e-04 - val_loss: 4.4784e-04 - 10s/epoch - 16ms/step
Epoch 5/100
657/657 - 10s - loss: 2.4398e-04 - val_loss: 2.5916e-04 - 10s/epoch - 16ms/step
Epoch 6/100
657/657 - 10s - loss: 3.5126e-04 - val_loss: 1.9026e-04 - 10s/epoch - 16ms/step
Epoch 7/100
657/657 - 10s - loss: 6.6379e-04 - val_loss: 4.2065e-04 - 10s/epoch - 16ms/step
Epoch 8/100
657/657 - 10s - loss: 9.9540e-04 - val_loss: 0.0011 - 10s/epoch - 16ms/step
Epoch 9/100
657/657 - 10s - loss: 9.3589e-04 - val_loss: 8.9071e-04 - 10s/epoch - 16ms/step
Epoch 10/100
657/657 - 10s - loss: 7.9155e-04 - val_loss: 5.7346e-04 - 10s/epoch - 16ms/step
Epoch 11/100
657/657 - 10s - loss: 6.4611e-04 - val_loss: 3.6802e-04 - 10s/epoch - 16ms/step
Ep

2023-03-21 10:44:28.600574: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:28.806725: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:28.824004: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:28.969557: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:28.990164: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:34.398212: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:34.463722: I tensorflow/core/grappler/optimizers/cust

329/329 - 8s - loss: 3.4033e-04 - val_loss: 6.7056e-04 - 8s/epoch - 23ms/step
Epoch 2/100
329/329 - 5s - loss: 5.5623e-04 - val_loss: 4.0809e-04 - 5s/epoch - 15ms/step
Epoch 3/100
329/329 - 5s - loss: 3.9330e-04 - val_loss: 2.3361e-04 - 5s/epoch - 16ms/step
Epoch 4/100
329/329 - 5s - loss: 3.0909e-04 - val_loss: 1.5827e-04 - 5s/epoch - 16ms/step
Epoch 5/100
329/329 - 5s - loss: 2.6715e-04 - val_loss: 1.2494e-04 - 5s/epoch - 16ms/step
Epoch 6/100
329/329 - 5s - loss: 2.4160e-04 - val_loss: 1.0467e-04 - 5s/epoch - 16ms/step
Epoch 7/100
329/329 - 5s - loss: 2.2023e-04 - val_loss: 9.0319e-05 - 5s/epoch - 16ms/step
Epoch 8/100
329/329 - 5s - loss: 2.0153e-04 - val_loss: 8.0102e-05 - 5s/epoch - 16ms/step
Epoch 9/100
329/329 - 5s - loss: 1.8518e-04 - val_loss: 7.2700e-05 - 5s/epoch - 16ms/step
Epoch 10/100
329/329 - 5s - loss: 1.7111e-04 - val_loss: 6.7122e-05 - 5s/epoch - 16ms/step
Epoch 11/100
329/329 - 5s - loss: 1.5937e-04 - val_loss: 6.2893e-05 - 5s/epoch - 16ms/step
Epoch 12/100
329/329

2023-03-21 10:53:11.123618: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:11.304545: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:11.325316: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:11.555111: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:11.576374: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:16.920241: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:16.979818: I tensorflow/core/grappler/optimizers/cust

329/329 - 8s - loss: 1.6902e-04 - val_loss: 7.6451e-05 - 8s/epoch - 24ms/step
Epoch 2/100
329/329 - 5s - loss: 2.1434e-04 - val_loss: 7.0830e-05 - 5s/epoch - 16ms/step
Epoch 3/100
329/329 - 5s - loss: 3.8761e-04 - val_loss: 5.1012e-04 - 5s/epoch - 16ms/step
Epoch 4/100
329/329 - 5s - loss: 3.6377e-04 - val_loss: 4.1492e-04 - 5s/epoch - 16ms/step
Epoch 5/100
329/329 - 5s - loss: 2.7657e-04 - val_loss: 2.4021e-04 - 5s/epoch - 16ms/step
Epoch 6/100
329/329 - 5s - loss: 1.9681e-04 - val_loss: 1.5613e-04 - 5s/epoch - 16ms/step
Epoch 7/100
329/329 - 6s - loss: 1.6513e-04 - val_loss: 1.1405e-04 - 6s/epoch - 17ms/step
Epoch 8/100
329/329 - 5s - loss: 1.5482e-04 - val_loss: 9.3922e-05 - 5s/epoch - 16ms/step
Epoch 9/100
329/329 - 5s - loss: 1.5270e-04 - val_loss: 8.9625e-05 - 5s/epoch - 16ms/step
Epoch 10/100
329/329 - 5s - loss: 1.5317e-04 - val_loss: 9.4385e-05 - 5s/epoch - 16ms/step
Epoch 11/100
329/329 - 5s - loss: 1.5342e-04 - val_loss: 1.0239e-04 - 5s/epoch - 16ms/step
Epoch 12/100
329/329

2023-03-21 11:01:57.489275: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:01:57.659114: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:01:57.673396: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:01:57.994244: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:01:58.013471: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:02:03.384018: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:02:03.445262: I tensorflow/core/grappler/optimizers/cust

329/329 - 8s - loss: 1.9301e-04 - val_loss: 1.1784e-04 - 8s/epoch - 24ms/step
Epoch 2/100
329/329 - 5s - loss: 2.7321e-04 - val_loss: 1.2689e-04 - 5s/epoch - 16ms/step
Epoch 3/100
329/329 - 5s - loss: 5.3232e-04 - val_loss: 9.1985e-04 - 5s/epoch - 16ms/step
Epoch 4/100
329/329 - 6s - loss: 4.6731e-04 - val_loss: 6.2778e-04 - 6s/epoch - 17ms/step
Epoch 5/100
329/329 - 5s - loss: 3.7427e-04 - val_loss: 3.8091e-04 - 5s/epoch - 17ms/step
Epoch 6/100
329/329 - 5s - loss: 2.6190e-04 - val_loss: 2.5873e-04 - 5s/epoch - 17ms/step
Epoch 7/100
329/329 - 5s - loss: 2.1125e-04 - val_loss: 1.9304e-04 - 5s/epoch - 16ms/step
Epoch 8/100
329/329 - 5s - loss: 1.9071e-04 - val_loss: 1.5603e-04 - 5s/epoch - 16ms/step
Epoch 9/100
329/329 - 5s - loss: 1.8461e-04 - val_loss: 1.4233e-04 - 5s/epoch - 16ms/step
Epoch 10/100
329/329 - 5s - loss: 1.8345e-04 - val_loss: 1.4325e-04 - 5s/epoch - 16ms/step
Epoch 11/100
329/329 - 5s - loss: 1.8266e-04 - val_loss: 1.4980e-04 - 5s/epoch - 16ms/step
Epoch 12/100
329/329

2023-03-21 11:10:59.388612: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:10:59.585343: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:10:59.601275: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:10:59.900094: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:10:59.920420: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:11:03.151460: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:11:03.216095: I tensorflow/core/grappler/optimizers/cust

165/165 - 6s - loss: 4.5737e-04 - val_loss: 1.5026e-04 - 6s/epoch - 35ms/step
Epoch 2/100
165/165 - 3s - loss: 0.0010 - val_loss: 0.0015 - 3s/epoch - 16ms/step
Epoch 3/100
165/165 - 3s - loss: 9.6717e-04 - val_loss: 9.0549e-04 - 3s/epoch - 16ms/step
Epoch 4/100
165/165 - 3s - loss: 6.9162e-04 - val_loss: 7.4638e-04 - 3s/epoch - 16ms/step
Epoch 5/100
165/165 - 3s - loss: 5.4427e-04 - val_loss: 5.0652e-04 - 3s/epoch - 16ms/step
Epoch 6/100
165/165 - 3s - loss: 4.4481e-04 - val_loss: 3.3906e-04 - 3s/epoch - 16ms/step
Epoch 7/100
165/165 - 3s - loss: 3.7927e-04 - val_loss: 2.3932e-04 - 3s/epoch - 16ms/step
Epoch 8/100
165/165 - 3s - loss: 3.3314e-04 - val_loss: 1.7871e-04 - 3s/epoch - 16ms/step
Epoch 9/100
165/165 - 3s - loss: 2.9684e-04 - val_loss: 1.3933e-04 - 3s/epoch - 16ms/step
Epoch 10/100
165/165 - 3s - loss: 2.6508e-04 - val_loss: 1.1099e-04 - 3s/epoch - 16ms/step
Epoch 11/100
165/165 - 3s - loss: 2.3549e-04 - val_loss: 8.9032e-05 - 3s/epoch - 16ms/step
Epoch 12/100
165/165 - 3s - 

2023-03-21 11:15:30.503109: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:30.678135: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:30.697532: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:31.105271: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:31.125733: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:34.331215: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:34.392384: I tensorflow/core/grappler/optimizers/cust

165/165 - 6s - loss: 3.7304e-04 - val_loss: 2.2295e-04 - 6s/epoch - 34ms/step
Epoch 2/100
165/165 - 3s - loss: 0.0011 - val_loss: 0.0021 - 3s/epoch - 16ms/step
Epoch 3/100
165/165 - 3s - loss: 0.0012 - val_loss: 0.0013 - 3s/epoch - 17ms/step
Epoch 4/100
165/165 - 3s - loss: 7.6272e-04 - val_loss: 9.1831e-04 - 3s/epoch - 17ms/step
Epoch 5/100
165/165 - 3s - loss: 5.2249e-04 - val_loss: 5.1657e-04 - 3s/epoch - 17ms/step
Epoch 6/100
165/165 - 3s - loss: 3.8685e-04 - val_loss: 3.0203e-04 - 3s/epoch - 17ms/step
Epoch 7/100
165/165 - 3s - loss: 3.0592e-04 - val_loss: 1.9477e-04 - 3s/epoch - 17ms/step
Epoch 8/100
165/165 - 3s - loss: 2.5023e-04 - val_loss: 1.3496e-04 - 3s/epoch - 17ms/step
Epoch 9/100
165/165 - 3s - loss: 2.0673e-04 - val_loss: 9.6000e-05 - 3s/epoch - 17ms/step
Epoch 10/100
165/165 - 3s - loss: 1.7227e-04 - val_loss: 6.7587e-05 - 3s/epoch - 17ms/step
Epoch 11/100
165/165 - 3s - loss: 1.4845e-04 - val_loss: 4.7798e-05 - 3s/epoch - 16ms/step
Epoch 12/100
165/165 - 3s - loss: 1.

2023-03-21 11:20:04.742143: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:04.923919: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:04.939649: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:05.113095: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:05.133747: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:08.457393: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:08.524244: I tensorflow/core/grappler/optimizers/cust

165/165 - 6s - loss: 4.3195e-04 - val_loss: 2.1298e-04 - 6s/epoch - 34ms/step
Epoch 2/100
165/165 - 3s - loss: 5.1004e-04 - val_loss: 6.4612e-04 - 3s/epoch - 17ms/step
Epoch 3/100
165/165 - 3s - loss: 0.0014 - val_loss: 0.0027 - 3s/epoch - 17ms/step
Epoch 4/100
165/165 - 3s - loss: 0.0023 - val_loss: 0.0038 - 3s/epoch - 17ms/step
Epoch 5/100
165/165 - 3s - loss: 0.0015 - val_loss: 0.0030 - 3s/epoch - 17ms/step
Epoch 6/100
165/165 - 3s - loss: 9.0385e-04 - val_loss: 0.0016 - 3s/epoch - 17ms/step
Epoch 7/100
165/165 - 3s - loss: 5.3801e-04 - val_loss: 6.8441e-04 - 3s/epoch - 17ms/step
Epoch 8/100
165/165 - 3s - loss: 3.6064e-04 - val_loss: 3.4218e-04 - 3s/epoch - 17ms/step
Epoch 9/100
165/165 - 3s - loss: 2.8278e-04 - val_loss: 2.0778e-04 - 3s/epoch - 17ms/step
Epoch 10/100
165/165 - 3s - loss: 2.4059e-04 - val_loss: 1.4606e-04 - 3s/epoch - 17ms/step
Epoch 11/100
165/165 - 3s - loss: 2.0985e-04 - val_loss: 1.1054e-04 - 3s/epoch - 17ms/step
Epoch 12/100
165/165 - 3s - loss: 1.8372e-04 - v

In [17]:
import pickle
i=0
for m in models:
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(bilstms[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].layer.units))
    print(Evaluation.mape(inv_y,inv_yhat)[0])
    with open('BiLSTM_ETH'+str(hyperparams[i])+'.pkl', 'wb') as f:
        pickle.dump(bilstms[i].history, f)
    i = i+1

2023-03-21 11:24:54.331249: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:24:54.403892: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:24:54.415420: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 7ms/step
(32, 100, 50)
Epoch: 100
Neurons: 50
0.9727266741287748


2023-03-21 11:24:56.079185: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:24:56.137552: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:24:56.149079: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 8ms/step
(32, 100, 60)
Epoch: 100
Neurons: 60
1.0082270394459278


2023-03-21 11:24:57.787692: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:24:57.846823: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:24:57.858077: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 8ms/step
(32, 100, 100)
Epoch: 100
Neurons: 100
1.0379958780592569
  1/165 [..............................] - ETA: 1:04

2023-03-21 11:24:59.524843: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:24:59.587680: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:24:59.599964: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 7ms/step
(64, 100, 50)
Epoch: 100
Neurons: 50
2.0638392753576222
  1/165 [..............................] - ETA: 1:05

2023-03-21 11:25:01.195198: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:01.252147: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:01.263544: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 7ms/step
(64, 100, 60)
Epoch: 100
Neurons: 60
2.8234429415994184


2023-03-21 11:25:02.853156: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:02.918053: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:02.929640: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 8ms/step
(64, 100, 100)
Epoch: 100
Neurons: 100
3.1398352932233515


2023-03-21 11:25:04.593692: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:04.659717: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:04.671374: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 7ms/step
(128, 100, 50)
Epoch: 100
Neurons: 50
1.8051899506852735


2023-03-21 11:25:06.260393: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:06.320696: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:06.334888: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 8ms/step
(128, 100, 60)
Epoch: 100
Neurons: 60
1.3700601023841479


2023-03-21 11:25:07.969425: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:08.026983: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:08.038600: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 2s 8ms/step
(128, 100, 100)
Epoch: 100
Neurons: 100
1.1039634961397684


In [18]:
with open('BiLSTM_ETH(32, 100, 50).pkl', "rb") as file_pi:
    history = pickle.load(file_pi)