In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook

In [2]:
ltc_dfd = pd.read_csv('../Dataset/Binance_LTCUSDT_1h.csv')
ltc_dfd

Unix                 Date   Symbol   Open   High    Low  \
0      1672527600000  2022-12-31 23:00:00  LTCUSDT  70.08  70.30  69.79   
1      1672524000000  2022-12-31 22:00:00  LTCUSDT  70.24  70.24  69.71   
2      1672520400000  2022-12-31 21:00:00  LTCUSDT  70.40  70.45  70.19   
3      1672516800000  2022-12-31 20:00:00  LTCUSDT  70.15  70.53  70.08   
4      1672513200000  2022-12-31 19:00:00  LTCUSDT  69.93  70.32  69.93   
...              ...                  ...      ...    ...    ...    ...   
26269  1577851200000  2020-01-01 04:00:00  LTCUSDT  41.53  41.85  41.45   
26270  1577847600000  2020-01-01 03:00:00  LTCUSDT  41.84  41.85  41.49   
26271  1577844000000  2020-01-01 02:00:00  LTCUSDT  41.63  41.88  41.62   
26272  1577840400000  2020-01-01 01:00:00  LTCUSDT  41.28  41.70  41.27   
26273  1577836800000  2020-01-01 00:00:00  LTCUSDT  41.29  41.29  41.16   

       Close   Volume LTC   Volume USDT  tradecount  
0      70.14  13547.20800  9.486568e+05        2306  
1      70.09  12617.98300  8.838422e+05        2288  
2      70.23   9698.22600  6.820723e+05        1580  
3      70.39  16666.36600  1.173164e+06        2150  
4      70.15  14214.55000  9.964355e+05        2499  
...      ...          ...           ...         ...  
26269  41.59   5317.81964  2.214516e+05         668  
26270  41.53   3873.02370  1.613043e+05         400  
26271  41.85   5757.19484  2.402871e+05         762  
26272  41.62   6814.68608  2.830715e+05         997  
26273  41.28   2828.06038  1.165827e+05         396  

[26274 rows x 10 columns]

In [3]:
df = Preprocessing.feature_selection(ltc_dfd)
df

Open   High    Low   Volume USDT  Close
0      41.29  41.29  41.16  1.165827e+05  41.28
1      41.28  41.70  41.27  2.830715e+05  41.62
2      41.63  41.88  41.62  2.402871e+05  41.85
3      41.84  41.85  41.49  1.613043e+05  41.53
4      41.53  41.85  41.45  2.214516e+05  41.59
...      ...    ...    ...           ...    ...
26269  69.93  70.32  69.93  9.964355e+05  70.15
26270  70.15  70.53  70.08  1.173164e+06  70.39
26271  70.40  70.45  70.19  6.820723e+05  70.23
26272  70.24  70.24  69.71  8.838422e+05  70.09
26273  70.08  70.30  69.79  9.486568e+05  70.14

[26274 rows x 5 columns]

In [4]:
df_no_dup = Preprocessing.handle_duplicate(df)
df_no_dup

duplicate ok


Open   High    Low   Volume USDT  Close
0      41.29  41.29  41.16  1.165827e+05  41.28
1      41.28  41.70  41.27  2.830715e+05  41.62
2      41.63  41.88  41.62  2.402871e+05  41.85
3      41.84  41.85  41.49  1.613043e+05  41.53
4      41.53  41.85  41.45  2.214516e+05  41.59
...      ...    ...    ...           ...    ...
26269  69.93  70.32  69.93  9.964355e+05  70.15
26270  70.15  70.53  70.08  1.173164e+06  70.39
26271  70.40  70.45  70.19  6.820723e+05  70.23
26272  70.24  70.24  69.71  8.838422e+05  70.09
26273  70.08  70.30  69.79  9.486568e+05  70.14

[26274 rows x 5 columns]

In [5]:
miss = Preprocessing.handle_missing_value(df_no_dup)
miss

No missing value


False

In [6]:
x, scaler = Preprocessing.minmax_scale(df_no_dup)
x

array([[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
       [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
       [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
       ...,
       [0.11742375, 0.10675971, 0.1219377 , 0.00159586, 0.11697868],
       [0.11700772, 0.10621289, 0.12067054, 0.00206794, 0.11661466],
       [0.1165917 , 0.10636913, 0.12088173, 0.00221959, 0.11674467]])

In [7]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
       [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
       [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
       ...,
       [0.10182272, 0.09230809, 0.1061246 , 0.00158488, 0.10208008],
       [0.10182272, 0.09178731, 0.10374868, 0.00463816, 0.09947998],
       [0.09922255, 0.09022498, 0.10295671, 0.00463943, 0.09869995]])

In [8]:
test

array([[0.0984425 , 0.08866264, 0.09873284, 0.00605067, 0.09427977],
       [0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
       [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
       ...,
       [0.11742375, 0.10675971, 0.1219377 , 0.00159586, 0.11697868],
       [0.11700772, 0.10621289, 0.12067054, 0.00206794, 0.11661466],
       [0.1165917 , 0.10636913, 0.12088173, 0.00221959, 0.11674467]])

In [9]:
train_X, train_y = Preprocessing.create_dataset(train,5)
test_X, test_y = Preprocessing.create_dataset(test,5)

In [10]:
train_X

array([[[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
        [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
        [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        [0.04316285, 0.0322883 , 0.04617212, 0.00037741, 0.04235569],
        [0.0423568 , 0.0322883 , 0.04606653, 0.00051813, 0.0425117 ]],

       [[0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
        [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        [0.04316285, 0.0322883 , 0.04617212, 0.00037741, 0.04235569],
        [0.0423568 , 0.0322883 , 0.04606653, 0.00051813, 0.0425117 ],
        [0.04256481, 0.03226226, 0.04643611, 0.00024607, 0.04300572]],

       [[0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        [0.04316285, 0.0322883 , 0.04617212, 0.00037741, 0.04235569],
        [0.0423568 , 0.0322883 , 0.04606653, 0.00051813, 0.0425117 ],
        [0.04256481, 0.03226226, 0.04643611, 0.00024607, 0.04300572],
        [0.04303

In [11]:
train_y

array([0.04300572, 0.0425897 , 0.0424857 , ..., 0.10208008, 0.09947998,
       0.09869995])

In [12]:
test_X

array([[[0.0984425 , 0.08866264, 0.09873284, 0.00605067, 0.09427977],
        [0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
        [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.09635985],
        [0.09610234, 0.08683991, 0.09794087, 0.00731901, 0.0950598 ]],

       [[0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
        [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.09635985],
        [0.09610234, 0.08683991, 0.09794087, 0.00731901, 0.0950598 ],
        [0.09480226, 0.08736069, 0.09794087, 0.00717084, 0.09791992]],

       [[0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.09635985],
        [0.09610234, 0.08683991, 0.09794087, 0.00731901, 0.0950598 ],
        [0.09480226, 0.08736069, 0.09794087, 0.00717084, 0.09791992],
        [0.09792

In [13]:
test_y

array([0.09791992, 0.09713989, 0.09687988, ..., 0.11697868, 0.11661466,
       0.11674467])

In [14]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(21014, 5, 5) (21014,) (5250, 5, 5) (5250,)


## Model Training

In [15]:
hyperparams = []
batch = [32, 64, 128]
epoch = [100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(32, 100, 50),
 (32, 100, 60),
 (32, 100, 100),
 (64, 100, 50),
 (64, 100, 60),
 (64, 100, 100),
 (128, 100, 50),
 (128, 100, 60),
 (128, 100, 100)]

In [16]:
bilstms = []
models = []
for batch, epoch, neuron in hyperparams:
    model, bilstm = LSTMUnit.train_bilstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    bilstms.append(bilstm)
    models.append(model)

Metal device set to: Apple M1
Epoch 1/100


2023-03-21 09:56:09.834197: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-21 09:56:09.834286: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-03-21 09:56:09.996910: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-03-21 09:56:11.246326: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 09:56:11.424121: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 09:56:11.455380: I tensorflow/core/grappler/o

657/657 - 14s - loss: 1.7017e-04 - val_loss: 1.9705e-05 - 14s/epoch - 21ms/step
Epoch 2/100
657/657 - 9s - loss: 1.7733e-04 - val_loss: 2.6717e-05 - 9s/epoch - 13ms/step
Epoch 3/100
657/657 - 9s - loss: 3.1728e-04 - val_loss: 3.5580e-05 - 9s/epoch - 14ms/step
Epoch 4/100
657/657 - 9s - loss: 7.1563e-04 - val_loss: 6.5755e-05 - 9s/epoch - 14ms/step
Epoch 5/100
657/657 - 9s - loss: 7.5823e-04 - val_loss: 7.0399e-05 - 9s/epoch - 14ms/step
Epoch 6/100
657/657 - 9s - loss: 5.1108e-04 - val_loss: 3.4501e-05 - 9s/epoch - 14ms/step
Epoch 7/100
657/657 - 9s - loss: 3.5233e-04 - val_loss: 1.6399e-05 - 9s/epoch - 14ms/step
Epoch 8/100
657/657 - 9s - loss: 2.6809e-04 - val_loss: 1.0274e-05 - 9s/epoch - 14ms/step
Epoch 9/100
657/657 - 9s - loss: 2.3261e-04 - val_loss: 8.5641e-06 - 9s/epoch - 14ms/step
Epoch 10/100
657/657 - 9s - loss: 2.2347e-04 - val_loss: 8.7530e-06 - 9s/epoch - 13ms/step
Epoch 11/100
657/657 - 9s - loss: 2.2838e-04 - val_loss: 9.4862e-06 - 9s/epoch - 13ms/step
Epoch 12/100
657/6

2023-03-21 10:11:15.386911: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:15.544594: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:15.557123: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:15.666783: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:15.685310: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:24.429733: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:11:24.485585: I tensorflow/core/grappler/optimizers/cust

657/657 - 11s - loss: 1.4739e-04 - val_loss: 2.0457e-05 - 11s/epoch - 17ms/step
Epoch 2/100
657/657 - 9s - loss: 1.3827e-04 - val_loss: 2.3643e-05 - 9s/epoch - 14ms/step
Epoch 3/100
657/657 - 9s - loss: 1.9092e-04 - val_loss: 3.1788e-05 - 9s/epoch - 14ms/step
Epoch 4/100
657/657 - 9s - loss: 3.4513e-04 - val_loss: 5.9606e-05 - 9s/epoch - 14ms/step
Epoch 5/100
657/657 - 9s - loss: 7.8759e-04 - val_loss: 1.0708e-04 - 9s/epoch - 14ms/step
Epoch 6/100
657/657 - 9s - loss: 7.9080e-04 - val_loss: 9.6466e-05 - 9s/epoch - 14ms/step
Epoch 7/100
657/657 - 9s - loss: 5.1834e-04 - val_loss: 4.5348e-05 - 9s/epoch - 14ms/step
Epoch 8/100
657/657 - 9s - loss: 3.4612e-04 - val_loss: 1.9224e-05 - 9s/epoch - 14ms/step
Epoch 9/100
657/657 - 9s - loss: 2.5460e-04 - val_loss: 1.0919e-05 - 9s/epoch - 14ms/step
Epoch 10/100
657/657 - 9s - loss: 2.1632e-04 - val_loss: 8.8960e-06 - 9s/epoch - 14ms/step
Epoch 11/100
657/657 - 9s - loss: 2.0743e-04 - val_loss: 8.8751e-06 - 9s/epoch - 14ms/step
Epoch 12/100
657/6

2023-03-21 10:27:19.717695: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:19.884034: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:19.897708: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:20.149684: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:20.170574: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:29.941401: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:27:30.000450: I tensorflow/core/grappler/optimizers/cust

657/657 - 13s - loss: 1.8262e-04 - val_loss: 3.0670e-05 - 13s/epoch - 20ms/step
Epoch 2/100
657/657 - 10s - loss: 1.6937e-04 - val_loss: 4.0253e-05 - 10s/epoch - 16ms/step
Epoch 3/100
657/657 - 10s - loss: 2.3307e-04 - val_loss: 4.6204e-05 - 10s/epoch - 16ms/step
Epoch 4/100
657/657 - 10s - loss: 4.1608e-04 - val_loss: 6.9242e-05 - 10s/epoch - 16ms/step
Epoch 5/100
657/657 - 10s - loss: 8.4385e-04 - val_loss: 2.1969e-04 - 10s/epoch - 16ms/step
Epoch 6/100
657/657 - 10s - loss: 0.0011 - val_loss: 2.8032e-04 - 10s/epoch - 16ms/step
Epoch 7/100
657/657 - 10s - loss: 7.2418e-04 - val_loss: 1.7209e-04 - 10s/epoch - 16ms/step
Epoch 8/100
657/657 - 10s - loss: 4.6839e-04 - val_loss: 6.7044e-05 - 10s/epoch - 16ms/step
Epoch 9/100
657/657 - 10s - loss: 3.1450e-04 - val_loss: 2.4292e-05 - 10s/epoch - 16ms/step
Epoch 10/100
657/657 - 10s - loss: 2.3757e-04 - val_loss: 1.2498e-05 - 10s/epoch - 16ms/step
Epoch 11/100
657/657 - 10s - loss: 2.1008e-04 - val_loss: 9.6688e-06 - 10s/epoch - 16ms/step
Ep

2023-03-21 10:44:38.227372: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:38.397757: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:38.412682: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:38.568901: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:38.588489: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:43.881751: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:44:43.941251: I tensorflow/core/grappler/optimizers/cust

329/329 - 8s - loss: 5.5081e-04 - val_loss: 6.2668e-05 - 8s/epoch - 23ms/step
Epoch 2/100
329/329 - 5s - loss: 1.9719e-04 - val_loss: 1.1597e-05 - 5s/epoch - 16ms/step
Epoch 3/100
329/329 - 5s - loss: 1.5082e-04 - val_loss: 7.2931e-06 - 5s/epoch - 16ms/step
Epoch 4/100
329/329 - 5s - loss: 1.3832e-04 - val_loss: 7.1243e-06 - 5s/epoch - 16ms/step
Epoch 5/100
329/329 - 5s - loss: 1.4385e-04 - val_loss: 7.5917e-06 - 5s/epoch - 16ms/step
Epoch 6/100
329/329 - 5s - loss: 1.5380e-04 - val_loss: 8.0030e-06 - 5s/epoch - 16ms/step
Epoch 7/100
329/329 - 5s - loss: 1.5892e-04 - val_loss: 8.0406e-06 - 5s/epoch - 16ms/step
Epoch 8/100
329/329 - 5s - loss: 1.5577e-04 - val_loss: 7.8489e-06 - 5s/epoch - 16ms/step
Epoch 9/100
329/329 - 5s - loss: 1.4842e-04 - val_loss: 7.6399e-06 - 5s/epoch - 16ms/step
Epoch 10/100
329/329 - 5s - loss: 1.4114e-04 - val_loss: 7.5320e-06 - 5s/epoch - 16ms/step
Epoch 11/100
329/329 - 5s - loss: 1.3578e-04 - val_loss: 7.5157e-06 - 5s/epoch - 16ms/step
Epoch 12/100
329/329

2023-03-21 10:53:21.221748: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:21.394192: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:21.409114: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:21.589823: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:21.610823: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:26.939018: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 10:53:27.000775: I tensorflow/core/grappler/optimizers/cust

329/329 - 8s - loss: 5.9197e-04 - val_loss: 1.6848e-04 - 8s/epoch - 24ms/step
Epoch 2/100
329/329 - 5s - loss: 3.8526e-04 - val_loss: 3.9050e-05 - 5s/epoch - 16ms/step
Epoch 3/100
329/329 - 5s - loss: 1.9440e-04 - val_loss: 9.5092e-06 - 5s/epoch - 16ms/step
Epoch 4/100
329/329 - 5s - loss: 1.3998e-04 - val_loss: 6.5005e-06 - 5s/epoch - 16ms/step
Epoch 5/100
329/329 - 6s - loss: 1.2487e-04 - val_loss: 6.5049e-06 - 6s/epoch - 17ms/step
Epoch 6/100
329/329 - 5s - loss: 1.3000e-04 - val_loss: 7.2545e-06 - 5s/epoch - 16ms/step
Epoch 7/100
329/329 - 5s - loss: 1.4271e-04 - val_loss: 8.1165e-06 - 5s/epoch - 16ms/step
Epoch 8/100
329/329 - 5s - loss: 1.5310e-04 - val_loss: 8.4806e-06 - 5s/epoch - 16ms/step
Epoch 9/100
329/329 - 5s - loss: 1.5359e-04 - val_loss: 8.3217e-06 - 5s/epoch - 16ms/step
Epoch 10/100
329/329 - 5s - loss: 1.4616e-04 - val_loss: 8.0152e-06 - 5s/epoch - 16ms/step
Epoch 11/100
329/329 - 5s - loss: 1.3716e-04 - val_loss: 7.8290e-06 - 5s/epoch - 16ms/step
Epoch 12/100
329/329

2023-03-21 11:02:07.957228: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:02:08.133389: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:02:08.147916: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:02:08.441559: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:02:08.461438: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:02:14.090092: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:02:14.151270: I tensorflow/core/grappler/optimizers/cust

329/329 - 8s - loss: 4.1793e-04 - val_loss: 8.7205e-05 - 8s/epoch - 25ms/step
Epoch 2/100
329/329 - 6s - loss: 5.5282e-04 - val_loss: 1.0143e-04 - 6s/epoch - 17ms/step
Epoch 3/100
329/329 - 6s - loss: 3.6207e-04 - val_loss: 4.5228e-05 - 6s/epoch - 17ms/step
Epoch 4/100
329/329 - 5s - loss: 2.2638e-04 - val_loss: 1.5235e-05 - 5s/epoch - 17ms/step
Epoch 5/100
329/329 - 5s - loss: 1.6889e-04 - val_loss: 9.1892e-06 - 5s/epoch - 16ms/step
Epoch 6/100
329/329 - 5s - loss: 1.5125e-04 - val_loss: 8.5066e-06 - 5s/epoch - 17ms/step
Epoch 7/100
329/329 - 5s - loss: 1.5374e-04 - val_loss: 9.1271e-06 - 5s/epoch - 16ms/step
Epoch 8/100
329/329 - 5s - loss: 1.6288e-04 - val_loss: 9.7569e-06 - 5s/epoch - 16ms/step
Epoch 9/100
329/329 - 5s - loss: 1.7130e-04 - val_loss: 1.0208e-05 - 5s/epoch - 16ms/step
Epoch 10/100
329/329 - 5s - loss: 1.7414e-04 - val_loss: 1.0480e-05 - 5s/epoch - 16ms/step
Epoch 11/100
329/329 - 5s - loss: 1.7082e-04 - val_loss: 1.0254e-05 - 5s/epoch - 16ms/step
Epoch 12/100
329/329

2023-03-21 11:11:15.285684: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:11:15.478364: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:11:15.494462: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:11:15.772523: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:11:15.792751: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:11:19.028469: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:11:19.090370: I tensorflow/core/grappler/optimizers/cust

165/165 - 6s - loss: 9.7019e-04 - val_loss: 7.2386e-04 - 6s/epoch - 35ms/step
Epoch 2/100
165/165 - 3s - loss: 5.2722e-04 - val_loss: 2.8726e-04 - 3s/epoch - 17ms/step
Epoch 3/100
165/165 - 3s - loss: 3.0349e-04 - val_loss: 1.2526e-04 - 3s/epoch - 17ms/step
Epoch 4/100
165/165 - 3s - loss: 1.8430e-04 - val_loss: 6.5168e-05 - 3s/epoch - 17ms/step
Epoch 5/100
165/165 - 3s - loss: 1.3850e-04 - val_loss: 4.0316e-05 - 3s/epoch - 17ms/step
Epoch 6/100
165/165 - 3s - loss: 1.3018e-04 - val_loss: 3.8357e-05 - 3s/epoch - 17ms/step
Epoch 7/100
165/165 - 3s - loss: 1.4264e-04 - val_loss: 5.1021e-05 - 3s/epoch - 17ms/step
Epoch 8/100
165/165 - 3s - loss: 1.7098e-04 - val_loss: 7.7040e-05 - 3s/epoch - 17ms/step
Epoch 9/100
165/165 - 3s - loss: 2.1341e-04 - val_loss: 1.2181e-04 - 3s/epoch - 16ms/step
Epoch 10/100
165/165 - 3s - loss: 2.7278e-04 - val_loss: 2.1282e-04 - 3s/epoch - 16ms/step
Epoch 11/100
165/165 - 3s - loss: 3.1986e-04 - val_loss: 3.0954e-04 - 3s/epoch - 16ms/step
Epoch 12/100
165/165

2023-03-21 11:15:48.829380: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:49.011662: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:49.027236: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:49.358515: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:49.378840: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:52.756814: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:15:52.819724: I tensorflow/core/grappler/optimizers/cust

165/165 - 6s - loss: 5.0689e-04 - val_loss: 2.0815e-04 - 6s/epoch - 35ms/step
Epoch 2/100
165/165 - 3s - loss: 2.6012e-04 - val_loss: 1.8644e-04 - 3s/epoch - 17ms/step
Epoch 3/100
165/165 - 3s - loss: 3.0698e-04 - val_loss: 2.1280e-04 - 3s/epoch - 17ms/step
Epoch 4/100
165/165 - 3s - loss: 4.0728e-04 - val_loss: 4.0882e-04 - 3s/epoch - 17ms/step
Epoch 5/100
165/165 - 3s - loss: 5.6649e-04 - val_loss: 7.7780e-04 - 3s/epoch - 17ms/step
Epoch 6/100
165/165 - 3s - loss: 5.2248e-04 - val_loss: 4.0865e-04 - 3s/epoch - 17ms/step
Epoch 7/100
165/165 - 3s - loss: 3.1094e-04 - val_loss: 1.6106e-04 - 3s/epoch - 17ms/step
Epoch 8/100
165/165 - 3s - loss: 1.7820e-04 - val_loss: 8.5702e-05 - 3s/epoch - 17ms/step
Epoch 9/100
165/165 - 3s - loss: 1.1654e-04 - val_loss: 5.6368e-05 - 3s/epoch - 17ms/step
Epoch 10/100
165/165 - 3s - loss: 9.4406e-05 - val_loss: 4.5051e-05 - 3s/epoch - 17ms/step
Epoch 11/100
165/165 - 3s - loss: 9.0167e-05 - val_loss: 4.4565e-05 - 3s/epoch - 17ms/step
Epoch 12/100
165/165

2023-03-21 11:20:24.843641: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:25.034518: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:25.049567: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:25.224826: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:25.245135: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:28.690008: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:20:28.751425: I tensorflow/core/grappler/optimizers/cust

165/165 - 6s - loss: 2.3221e-04 - val_loss: 1.8749e-05 - 6s/epoch - 35ms/step
Epoch 2/100
165/165 - 3s - loss: 1.7737e-04 - val_loss: 1.8395e-05 - 3s/epoch - 18ms/step
Epoch 3/100
165/165 - 3s - loss: 1.6095e-04 - val_loss: 7.7439e-06 - 3s/epoch - 19ms/step
Epoch 4/100
165/165 - 3s - loss: 9.6451e-05 - val_loss: 6.2617e-06 - 3s/epoch - 18ms/step
Epoch 5/100
165/165 - 3s - loss: 9.1698e-05 - val_loss: 7.5819e-06 - 3s/epoch - 18ms/step
Epoch 6/100
165/165 - 3s - loss: 9.0008e-05 - val_loss: 7.9259e-06 - 3s/epoch - 18ms/step
Epoch 7/100
165/165 - 3s - loss: 8.8741e-05 - val_loss: 7.8869e-06 - 3s/epoch - 18ms/step
Epoch 8/100
165/165 - 3s - loss: 8.7226e-05 - val_loss: 7.7609e-06 - 3s/epoch - 18ms/step
Epoch 9/100
165/165 - 3s - loss: 8.5541e-05 - val_loss: 7.6159e-06 - 3s/epoch - 18ms/step
Epoch 10/100
165/165 - 3s - loss: 8.3824e-05 - val_loss: 7.4688e-06 - 3s/epoch - 18ms/step
Epoch 11/100
165/165 - 3s - loss: 8.2126e-05 - val_loss: 7.3240e-06 - 3s/epoch - 18ms/step
Epoch 12/100
165/165

In [17]:
import pickle
i=0
for m in models:
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(bilstms[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].layer.units))
    print(Evaluation.mape(inv_y,inv_yhat)[0])
    with open('BiLSTM_LTC'+str(hyperparams[i])+'.pkl', 'wb') as f:
        pickle.dump(bilstms[i].history, f)
    i = i+1

  1/165 [..............................] - ETA: 1:33

2023-03-21 11:25:21.931906: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:21.984149: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:21.992353: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(32, 100, 50)
Epoch: 100
Neurons: 50
0.7770220056128813
  1/165 [..............................] - ETA: 49s

2023-03-21 11:25:23.157423: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:23.202178: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:23.210308: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(32, 100, 60)
Epoch: 100
Neurons: 60
0.7280671044116247
  1/165 [..............................] - ETA: 48s

2023-03-21 11:25:24.315969: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:24.357560: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:24.365977: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(32, 100, 100)
Epoch: 100
Neurons: 100
0.7380658879830945
  1/165 [..............................] - ETA: 47s

2023-03-21 11:25:25.515421: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:25.559100: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:25.567385: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(64, 100, 50)
Epoch: 100
Neurons: 50
0.9293664757803509
  1/165 [..............................] - ETA: 47s

2023-03-21 11:25:26.661175: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:26.703883: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:26.712419: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(64, 100, 60)
Epoch: 100
Neurons: 60
0.9065518074965541
  1/165 [..............................] - ETA: 47s

2023-03-21 11:25:27.790752: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:27.834339: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:27.842849: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(64, 100, 100)
Epoch: 100
Neurons: 100
0.8105218143526441
  1/165 [..............................] - ETA: 49s

2023-03-21 11:25:28.994292: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:29.044246: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:29.052476: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(128, 100, 50)
Epoch: 100
Neurons: 50
4.333149706743311
  4/165 [..............................] - ETA: 2s 

2023-03-21 11:25:30.152294: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:30.194184: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:30.202388: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(128, 100, 60)
Epoch: 100
Neurons: 60
4.289900325950248
  1/165 [..............................] - ETA: 48s

2023-03-21 11:25:31.293631: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:31.335573: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 11:25:31.343758: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 5ms/step
(128, 100, 100)
Epoch: 100
Neurons: 100
0.8854880516837641


In [18]:
with open('BiLSTM_LTC(32, 100, 50).pkl', "rb") as file_pi:
    history = pickle.load(file_pi)