In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook

In [2]:
ltc_dfd = pd.read_csv('../Dataset/Binance_LTCUSDT_1h.csv')
ltc_dfd

Unix                 Date   Symbol   Open   High    Low  \
0      1672527600000  2022-12-31 23:00:00  LTCUSDT  70.08  70.30  69.79   
1      1672524000000  2022-12-31 22:00:00  LTCUSDT  70.24  70.24  69.71   
2      1672520400000  2022-12-31 21:00:00  LTCUSDT  70.40  70.45  70.19   
3      1672516800000  2022-12-31 20:00:00  LTCUSDT  70.15  70.53  70.08   
4      1672513200000  2022-12-31 19:00:00  LTCUSDT  69.93  70.32  69.93   
...              ...                  ...      ...    ...    ...    ...   
26269  1577851200000  2020-01-01 04:00:00  LTCUSDT  41.53  41.85  41.45   
26270  1577847600000  2020-01-01 03:00:00  LTCUSDT  41.84  41.85  41.49   
26271  1577844000000  2020-01-01 02:00:00  LTCUSDT  41.63  41.88  41.62   
26272  1577840400000  2020-01-01 01:00:00  LTCUSDT  41.28  41.70  41.27   
26273  1577836800000  2020-01-01 00:00:00  LTCUSDT  41.29  41.29  41.16   

       Close   Volume LTC   Volume USDT  tradecount  
0      70.14  13547.20800  9.486568e+05        2306  
1      70.09  12617.98300  8.838422e+05        2288  
2      70.23   9698.22600  6.820723e+05        1580  
3      70.39  16666.36600  1.173164e+06        2150  
4      70.15  14214.55000  9.964355e+05        2499  
...      ...          ...           ...         ...  
26269  41.59   5317.81964  2.214516e+05         668  
26270  41.53   3873.02370  1.613043e+05         400  
26271  41.85   5757.19484  2.402871e+05         762  
26272  41.62   6814.68608  2.830715e+05         997  
26273  41.28   2828.06038  1.165827e+05         396  

[26274 rows x 10 columns]

In [3]:
df = Preprocessing.feature_selection(ltc_dfd)
df

Open   High    Low   Volume USDT  Close
0      41.29  41.29  41.16  1.165827e+05  41.28
1      41.28  41.70  41.27  2.830715e+05  41.62
2      41.63  41.88  41.62  2.402871e+05  41.85
3      41.84  41.85  41.49  1.613043e+05  41.53
4      41.53  41.85  41.45  2.214516e+05  41.59
...      ...    ...    ...           ...    ...
26269  69.93  70.32  69.93  9.964355e+05  70.15
26270  70.15  70.53  70.08  1.173164e+06  70.39
26271  70.40  70.45  70.19  6.820723e+05  70.23
26272  70.24  70.24  69.71  8.838422e+05  70.09
26273  70.08  70.30  69.79  9.486568e+05  70.14

[26274 rows x 5 columns]

In [4]:
df_no_dup = Preprocessing.handle_duplicate(df)
df_no_dup

duplicate ok


Open   High    Low   Volume USDT  Close
0      41.29  41.29  41.16  1.165827e+05  41.28
1      41.28  41.70  41.27  2.830715e+05  41.62
2      41.63  41.88  41.62  2.402871e+05  41.85
3      41.84  41.85  41.49  1.613043e+05  41.53
4      41.53  41.85  41.45  2.214516e+05  41.59
...      ...    ...    ...           ...    ...
26269  69.93  70.32  69.93  9.964355e+05  70.15
26270  70.15  70.53  70.08  1.173164e+06  70.39
26271  70.40  70.45  70.19  6.820723e+05  70.23
26272  70.24  70.24  69.71  8.838422e+05  70.09
26273  70.08  70.30  69.79  9.486568e+05  70.14

[26274 rows x 5 columns]

In [5]:
miss = Preprocessing.handle_missing_value(df_no_dup)
miss

No missing value


False

In [6]:
x, scaler = Preprocessing.minmax_scale(df_no_dup)
x

array([[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
       [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
       [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
       ...,
       [0.11742375, 0.10675971, 0.1219377 , 0.00159586, 0.11697868],
       [0.11700772, 0.10621289, 0.12067054, 0.00206794, 0.11661466],
       [0.1165917 , 0.10636913, 0.12088173, 0.00221959, 0.11674467]])

In [7]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
       [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
       [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
       ...,
       [0.10182272, 0.09230809, 0.1061246 , 0.00158488, 0.10208008],
       [0.10182272, 0.09178731, 0.10374868, 0.00463816, 0.09947998],
       [0.09922255, 0.09022498, 0.10295671, 0.00463943, 0.09869995]])

In [8]:
test

array([[0.0984425 , 0.08866264, 0.09873284, 0.00605067, 0.09427977],
       [0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
       [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
       ...,
       [0.11742375, 0.10675971, 0.1219377 , 0.00159586, 0.11697868],
       [0.11700772, 0.10621289, 0.12067054, 0.00206794, 0.11661466],
       [0.1165917 , 0.10636913, 0.12088173, 0.00221959, 0.11674467]])

In [9]:
train_X, train_y = Preprocessing.create_dataset(train,5)
test_X, test_y = Preprocessing.create_dataset(test,5)

In [10]:
train_X

array([[[0.04173275, 0.03083012, 0.04530095, 0.00027277, 0.04170567],
        [0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
        [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        [0.04316285, 0.0322883 , 0.04617212, 0.00037741, 0.04235569],
        [0.0423568 , 0.0322883 , 0.04606653, 0.00051813, 0.0425117 ]],

       [[0.04170675, 0.03189772, 0.04559134, 0.00066231, 0.0425897 ],
        [0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        [0.04316285, 0.0322883 , 0.04617212, 0.00037741, 0.04235569],
        [0.0423568 , 0.0322883 , 0.04606653, 0.00051813, 0.0425117 ],
        [0.04256481, 0.03226226, 0.04643611, 0.00024607, 0.04300572]],

       [[0.04261681, 0.03236642, 0.04651531, 0.0005622 , 0.04318773],
        [0.04316285, 0.0322883 , 0.04617212, 0.00037741, 0.04235569],
        [0.0423568 , 0.0322883 , 0.04606653, 0.00051813, 0.0425117 ],
        [0.04256481, 0.03226226, 0.04643611, 0.00024607, 0.04300572],
        [0.04303

In [11]:
train_y

array([0.04300572, 0.0425897 , 0.0424857 , ..., 0.10208008, 0.09947998,
       0.09869995])

In [12]:
test_X

array([[[0.0984425 , 0.08866264, 0.09873284, 0.00605067, 0.09427977],
        [0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
        [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.09635985],
        [0.09610234, 0.08683991, 0.09794087, 0.00731901, 0.0950598 ]],

       [[0.09454224, 0.08579835, 0.09794087, 0.00786288, 0.09557982],
        [0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.09635985],
        [0.09610234, 0.08683991, 0.09794087, 0.00731901, 0.0950598 ],
        [0.09480226, 0.08736069, 0.09794087, 0.00717084, 0.09791992]],

       [[0.09584233, 0.08892303, 0.1000528 , 0.00411582, 0.09791992],
        [0.09818248, 0.08840225, 0.10058078, 0.00425213, 0.09635985],
        [0.09610234, 0.08683991, 0.09794087, 0.00731901, 0.0950598 ],
        [0.09480226, 0.08736069, 0.09794087, 0.00717084, 0.09791992],
        [0.09792

In [13]:
test_y

array([0.09791992, 0.09713989, 0.09687988, ..., 0.11697868, 0.11661466,
       0.11674467])

In [14]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(21014, 5, 5) (21014,) (5250, 5, 5) (5250,)


## Model Training

In [15]:
hyperparams = []
batch = [32, 64, 128]
epoch = [100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(32, 100, 50),
 (32, 100, 60),
 (32, 100, 100),
 (64, 100, 50),
 (64, 100, 60),
 (64, 100, 100),
 (128, 100, 50),
 (128, 100, 60),
 (128, 100, 100)]

In [16]:
lstms = []
models = []
for batch, epoch, neuron in hyperparams:
    model, lstm = LSTMUnit.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms.append(lstm)
    models.append(model)

Metal device set to: Apple M1


2023-03-21 23:20:34.556699: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-21 23:20:34.556784: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Epoch 1/100


2023-03-21 23:20:34.778675: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-03-21 23:20:35.264933: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:20:35.351320: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:20:35.489172: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:20:40.565969: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:20:40.598276: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 6s - loss: 2.6136e-04 - mse: 2.6136e-04 - val_loss: 3.9358e-05 - val_mse: 3.9358e-05 - 6s/epoch - 10ms/step
Epoch 2/100
657/657 - 5s - loss: 3.4696e-04 - mse: 3.4696e-04 - val_loss: 8.6818e-05 - val_mse: 8.6818e-05 - 5s/epoch - 8ms/step
Epoch 3/100
657/657 - 5s - loss: 7.8446e-04 - mse: 7.8446e-04 - val_loss: 1.1806e-04 - val_mse: 1.1806e-04 - 5s/epoch - 8ms/step
Epoch 4/100
657/657 - 5s - loss: 6.4573e-04 - mse: 6.4573e-04 - val_loss: 9.6003e-05 - val_mse: 9.6003e-05 - 5s/epoch - 8ms/step
Epoch 5/100
657/657 - 5s - loss: 4.2957e-04 - mse: 4.2957e-04 - val_loss: 4.6804e-05 - val_mse: 4.6804e-05 - 5s/epoch - 8ms/step
Epoch 6/100
657/657 - 5s - loss: 2.9430e-04 - mse: 2.9430e-04 - val_loss: 2.2660e-05 - val_mse: 2.2660e-05 - 5s/epoch - 8ms/step
Epoch 7/100
657/657 - 5s - loss: 2.2318e-04 - mse: 2.2318e-04 - val_loss: 1.4002e-05 - val_mse: 1.4002e-05 - 5s/epoch - 8ms/step
Epoch 8/100
657/657 - 5s - loss: 1.9471e-04 - mse: 1.9471e-04 - val_loss: 1.1623e-05 - val_mse: 1.1623e-05 -

2023-03-21 23:29:36.242363: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:29:36.351699: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:29:36.450253: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:29:41.647659: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:29:41.683194: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 7s - loss: 1.2494e-04 - mse: 1.2494e-04 - val_loss: 2.2230e-05 - val_mse: 2.2230e-05 - 7s/epoch - 10ms/step
Epoch 2/100
657/657 - 6s - loss: 1.2355e-04 - mse: 1.2355e-04 - val_loss: 2.8689e-05 - val_mse: 2.8689e-05 - 6s/epoch - 8ms/step
Epoch 3/100
657/657 - 6s - loss: 1.9258e-04 - mse: 1.9258e-04 - val_loss: 4.0247e-05 - val_mse: 4.0247e-05 - 6s/epoch - 8ms/step
Epoch 4/100
657/657 - 6s - loss: 3.9772e-04 - mse: 3.9772e-04 - val_loss: 1.1542e-04 - val_mse: 1.1542e-04 - 6s/epoch - 8ms/step
Epoch 5/100
657/657 - 6s - loss: 7.9710e-04 - mse: 7.9710e-04 - val_loss: 1.7717e-04 - val_mse: 1.7717e-04 - 6s/epoch - 8ms/step
Epoch 6/100
657/657 - 6s - loss: 5.6254e-04 - mse: 5.6254e-04 - val_loss: 1.0651e-04 - val_mse: 1.0651e-04 - 6s/epoch - 8ms/step
Epoch 7/100
657/657 - 6s - loss: 3.5841e-04 - mse: 3.5841e-04 - val_loss: 4.7935e-05 - val_mse: 4.7935e-05 - 6s/epoch - 9ms/step
Epoch 8/100
657/657 - 6s - loss: 2.3803e-04 - mse: 2.3803e-04 - val_loss: 2.0913e-05 - val_mse: 2.0913e-05 -

2023-03-21 23:39:03.906039: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:39:04.000795: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:39:04.093792: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:39:09.411853: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:39:09.449329: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 7s - loss: 1.4565e-04 - mse: 1.4565e-04 - val_loss: 3.3262e-05 - val_mse: 3.3262e-05 - 7s/epoch - 10ms/step
Epoch 2/100
657/657 - 6s - loss: 1.5388e-04 - mse: 1.5388e-04 - val_loss: 4.8136e-05 - val_mse: 4.8136e-05 - 6s/epoch - 9ms/step
Epoch 3/100
657/657 - 6s - loss: 2.3871e-04 - mse: 2.3871e-04 - val_loss: 9.4669e-05 - val_mse: 9.4669e-05 - 6s/epoch - 9ms/step
Epoch 4/100
657/657 - 6s - loss: 4.6397e-04 - mse: 4.6397e-04 - val_loss: 2.1106e-04 - val_mse: 2.1106e-04 - 6s/epoch - 9ms/step
Epoch 5/100
657/657 - 6s - loss: 9.5345e-04 - mse: 9.5345e-04 - val_loss: 3.3881e-04 - val_mse: 3.3881e-04 - 6s/epoch - 9ms/step
Epoch 6/100
657/657 - 6s - loss: 7.1295e-04 - mse: 7.1295e-04 - val_loss: 2.4240e-04 - val_mse: 2.4240e-04 - 6s/epoch - 9ms/step
Epoch 7/100
657/657 - 6s - loss: 4.5062e-04 - mse: 4.5062e-04 - val_loss: 1.1149e-04 - val_mse: 1.1149e-04 - 6s/epoch - 9ms/step
Epoch 8/100
657/657 - 6s - loss: 2.8138e-04 - mse: 2.8138e-04 - val_loss: 4.0952e-05 - val_mse: 4.0952e-05 -

2023-03-21 23:49:04.959030: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:49:05.064611: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:49:05.170206: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:49:08.214433: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:49:08.252954: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 4s - loss: 5.1534e-04 - mse: 5.1534e-04 - val_loss: 1.9819e-04 - val_mse: 1.9819e-04 - 4s/epoch - 14ms/step
Epoch 2/100
329/329 - 3s - loss: 2.8514e-04 - mse: 2.8514e-04 - val_loss: 6.2858e-05 - val_mse: 6.2858e-05 - 3s/epoch - 9ms/step
Epoch 3/100
329/329 - 3s - loss: 1.8200e-04 - mse: 1.8200e-04 - val_loss: 2.1824e-05 - val_mse: 2.1824e-05 - 3s/epoch - 9ms/step
Epoch 4/100
329/329 - 3s - loss: 1.3785e-04 - mse: 1.3785e-04 - val_loss: 1.2629e-05 - val_mse: 1.2629e-05 - 3s/epoch - 9ms/step
Epoch 5/100
329/329 - 3s - loss: 1.2466e-04 - mse: 1.2466e-04 - val_loss: 1.0620e-05 - val_mse: 1.0620e-05 - 3s/epoch - 9ms/step
Epoch 6/100
329/329 - 3s - loss: 1.2475e-04 - mse: 1.2475e-04 - val_loss: 1.0278e-05 - val_mse: 1.0278e-05 - 3s/epoch - 9ms/step
Epoch 7/100
329/329 - 3s - loss: 1.2790e-04 - mse: 1.2790e-04 - val_loss: 1.0093e-05 - val_mse: 1.0093e-05 - 3s/epoch - 9ms/step
Epoch 8/100
329/329 - 3s - loss: 1.2814e-04 - mse: 1.2814e-04 - val_loss: 9.6815e-06 - val_mse: 9.6815e-06 -

2023-03-21 23:54:13.525062: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:54:13.628039: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:54:13.742705: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:54:16.762337: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:54:16.800097: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 4s - loss: 5.4793e-04 - mse: 5.4793e-04 - val_loss: 1.7832e-04 - val_mse: 1.7832e-04 - 4s/epoch - 13ms/step
Epoch 2/100
329/329 - 3s - loss: 2.9206e-04 - mse: 2.9206e-04 - val_loss: 3.2915e-05 - val_mse: 3.2915e-05 - 3s/epoch - 9ms/step
Epoch 3/100
329/329 - 3s - loss: 1.7387e-04 - mse: 1.7387e-04 - val_loss: 9.9186e-06 - val_mse: 9.9186e-06 - 3s/epoch - 9ms/step
Epoch 4/100
329/329 - 3s - loss: 1.2607e-04 - mse: 1.2607e-04 - val_loss: 6.9352e-06 - val_mse: 6.9352e-06 - 3s/epoch - 10ms/step
Epoch 5/100
329/329 - 3s - loss: 1.1423e-04 - mse: 1.1423e-04 - val_loss: 7.1308e-06 - val_mse: 7.1308e-06 - 3s/epoch - 9ms/step
Epoch 6/100
329/329 - 3s - loss: 1.2121e-04 - mse: 1.2121e-04 - val_loss: 8.1698e-06 - val_mse: 8.1698e-06 - 3s/epoch - 9ms/step
Epoch 7/100
329/329 - 3s - loss: 1.3482e-04 - mse: 1.3482e-04 - val_loss: 9.2807e-06 - val_mse: 9.2807e-06 - 3s/epoch - 9ms/step
Epoch 8/100
329/329 - 3s - loss: 1.4478e-04 - mse: 1.4478e-04 - val_loss: 9.7563e-06 - val_mse: 9.7563e-06 

2023-03-21 23:59:22.998027: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:59:23.103627: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:59:23.213670: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:59:26.330099: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:59:26.367064: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 4s - loss: 5.5875e-04 - mse: 5.5875e-04 - val_loss: 2.7132e-04 - val_mse: 2.7132e-04 - 4s/epoch - 13ms/step
Epoch 2/100
329/329 - 3s - loss: 3.7768e-04 - mse: 3.7768e-04 - val_loss: 1.1020e-04 - val_mse: 1.1020e-04 - 3s/epoch - 9ms/step
Epoch 3/100
329/329 - 3s - loss: 2.3105e-04 - mse: 2.3105e-04 - val_loss: 4.0919e-05 - val_mse: 4.0919e-05 - 3s/epoch - 10ms/step
Epoch 4/100
329/329 - 3s - loss: 1.6548e-04 - mse: 1.6548e-04 - val_loss: 2.0748e-05 - val_mse: 2.0748e-05 - 3s/epoch - 10ms/step
Epoch 5/100
329/329 - 3s - loss: 1.4109e-04 - mse: 1.4109e-04 - val_loss: 1.5716e-05 - val_mse: 1.5716e-05 - 3s/epoch - 9ms/step
Epoch 6/100
329/329 - 3s - loss: 1.3949e-04 - mse: 1.3949e-04 - val_loss: 1.4915e-05 - val_mse: 1.4915e-05 - 3s/epoch - 9ms/step
Epoch 7/100
329/329 - 3s - loss: 1.4660e-04 - mse: 1.4660e-04 - val_loss: 1.4880e-05 - val_mse: 1.4880e-05 - 3s/epoch - 9ms/step
Epoch 8/100
329/329 - 3s - loss: 1.5324e-04 - mse: 1.5324e-04 - val_loss: 1.4437e-05 - val_mse: 1.4437e-05

2023-03-22 00:04:42.485792: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:04:42.589905: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:04:42.705837: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:04:44.477832: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:04:44.516089: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 3s - loss: 7.0871e-04 - mse: 7.0871e-04 - val_loss: 4.2086e-04 - val_mse: 4.2086e-04 - 3s/epoch - 17ms/step
Epoch 2/100
165/165 - 2s - loss: 1.9267e-04 - mse: 1.9267e-04 - val_loss: 2.4444e-04 - val_mse: 2.4444e-04 - 2s/epoch - 10ms/step
Epoch 3/100
165/165 - 2s - loss: 1.6771e-04 - mse: 1.6771e-04 - val_loss: 1.7748e-04 - val_mse: 1.7748e-04 - 2s/epoch - 10ms/step
Epoch 4/100
165/165 - 2s - loss: 1.7235e-04 - mse: 1.7235e-04 - val_loss: 1.5207e-04 - val_mse: 1.5207e-04 - 2s/epoch - 10ms/step
Epoch 5/100
165/165 - 2s - loss: 2.1326e-04 - mse: 2.1326e-04 - val_loss: 1.7355e-04 - val_mse: 1.7355e-04 - 2s/epoch - 11ms/step
Epoch 6/100
165/165 - 2s - loss: 3.2595e-04 - mse: 3.2595e-04 - val_loss: 3.7850e-04 - val_mse: 3.7850e-04 - 2s/epoch - 10ms/step
Epoch 7/100
165/165 - 2s - loss: 5.1099e-04 - mse: 5.1099e-04 - val_loss: 8.3166e-04 - val_mse: 8.3166e-04 - 2s/epoch - 10ms/step
Epoch 8/100
165/165 - 2s - loss: 5.5130e-04 - mse: 5.5130e-04 - val_loss: 5.3771e-04 - val_mse: 5.3771

2023-03-22 00:07:26.845039: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:07:26.955280: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:07:27.093581: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:07:28.851653: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:07:28.889026: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 3s - loss: 7.3685e-04 - mse: 7.3685e-04 - val_loss: 0.0011 - val_mse: 0.0011 - 3s/epoch - 18ms/step
Epoch 2/100
165/165 - 2s - loss: 5.6670e-04 - mse: 5.6670e-04 - val_loss: 7.6253e-04 - val_mse: 7.6253e-04 - 2s/epoch - 9ms/step
Epoch 3/100
165/165 - 2s - loss: 4.5089e-04 - mse: 4.5089e-04 - val_loss: 4.2573e-04 - val_mse: 4.2573e-04 - 2s/epoch - 9ms/step
Epoch 4/100
165/165 - 2s - loss: 2.9036e-04 - mse: 2.9036e-04 - val_loss: 2.5406e-04 - val_mse: 2.5406e-04 - 2s/epoch - 10ms/step
Epoch 5/100
165/165 - 2s - loss: 1.8411e-04 - mse: 1.8411e-04 - val_loss: 1.7060e-04 - val_mse: 1.7060e-04 - 2s/epoch - 10ms/step
Epoch 6/100
165/165 - 2s - loss: 1.3365e-04 - mse: 1.3365e-04 - val_loss: 1.2518e-04 - val_mse: 1.2518e-04 - 2s/epoch - 9ms/step
Epoch 7/100
165/165 - 2s - loss: 1.1655e-04 - mse: 1.1655e-04 - val_loss: 1.0469e-04 - val_mse: 1.0469e-04 - 2s/epoch - 9ms/step
Epoch 8/100
165/165 - 2s - loss: 1.1746e-04 - mse: 1.1746e-04 - val_loss: 1.0319e-04 - val_mse: 1.0319e-04 - 2s/ep

2023-03-22 00:10:02.698203: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:10:02.803599: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:10:02.939746: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:10:04.794358: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:10:04.832755: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 3s - loss: 7.6610e-04 - mse: 7.6610e-04 - val_loss: 9.6739e-04 - val_mse: 9.6739e-04 - 3s/epoch - 18ms/step
Epoch 2/100
165/165 - 2s - loss: 4.8546e-04 - mse: 4.8546e-04 - val_loss: 0.0010 - val_mse: 0.0010 - 2s/epoch - 10ms/step
Epoch 3/100
165/165 - 2s - loss: 5.7667e-04 - mse: 5.7667e-04 - val_loss: 0.0012 - val_mse: 0.0012 - 2s/epoch - 10ms/step
Epoch 4/100
165/165 - 2s - loss: 6.1880e-04 - mse: 6.1880e-04 - val_loss: 8.5060e-04 - val_mse: 8.5060e-04 - 2s/epoch - 10ms/step
Epoch 5/100
165/165 - 2s - loss: 4.6699e-04 - mse: 4.6699e-04 - val_loss: 5.2124e-04 - val_mse: 5.2124e-04 - 2s/epoch - 10ms/step
Epoch 6/100
165/165 - 2s - loss: 2.9660e-04 - mse: 2.9660e-04 - val_loss: 3.5285e-04 - val_mse: 3.5285e-04 - 2s/epoch - 10ms/step
Epoch 7/100
165/165 - 2s - loss: 1.8929e-04 - mse: 1.8929e-04 - val_loss: 2.6247e-04 - val_mse: 2.6247e-04 - 2s/epoch - 10ms/step
Epoch 8/100
165/165 - 2s - loss: 1.3707e-04 - mse: 1.3707e-04 - val_loss: 2.1023e-04 - val_mse: 2.1023e-04 - 2s/epoch 

In [17]:
import pickle
i=0
for m in models:
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(lstms[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].units))
    print(Evaluation.mape(inv_y,inv_yhat)[0])
    with open('LSTM_LTC'+str(hyperparams[i])+'.pkl', 'wb') as f:
        pickle.dump(lstms[i].history, f)
    i = i+1

 11/165 [=>............................] - ETA: 0s 

2023-03-22 00:12:52.654455: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:52.690671: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 4ms/step
(32, 100, 50)
Epoch: 100
Neurons: 50
0.843096042510455
 10/165 [>.............................] - ETA: 0s 

2023-03-22 00:12:53.549284: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:53.582348: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 4ms/step
(32, 100, 60)
Epoch: 100
Neurons: 60
0.8632753752123327
 12/165 [=>............................] - ETA: 0s 

2023-03-22 00:12:54.394563: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:54.426049: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 4ms/step
(32, 100, 100)
Epoch: 100
Neurons: 100
0.7570960571156241
 11/165 [=>............................] - ETA: 0s 

2023-03-22 00:12:55.235480: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:55.266397: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 4ms/step
(64, 100, 50)
Epoch: 100
Neurons: 50
0.9371668992681773
 12/165 [=>............................] - ETA: 0s 

2023-03-22 00:12:56.077172: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:56.111415: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 4ms/step
(64, 100, 60)
Epoch: 100
Neurons: 60
0.857605255015397
 10/165 [>.............................] - ETA: 0s 

2023-03-22 00:12:56.909368: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:56.940453: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(64, 100, 100)
Epoch: 100
Neurons: 100
0.945761073480084
 11/165 [=>............................] - ETA: 0s 

2023-03-22 00:12:57.743810: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:57.778642: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 4ms/step
(128, 100, 50)
Epoch: 100
Neurons: 50
3.5066941997869314
 11/165 [=>............................] - ETA: 0s 

2023-03-22 00:12:58.582946: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:58.615257: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 4ms/step
(128, 100, 60)
Epoch: 100
Neurons: 60
3.9665127736439993
 11/165 [=>............................] - ETA: 0s 

2023-03-22 00:12:59.431960: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:12:59.464293: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 4ms/step
(128, 100, 100)
Epoch: 100
Neurons: 100
4.012236076859919


In [18]:
with open('LSTM_LTC(32, 100, 50).pkl', "rb") as file_pi:
    history = pickle.load(file_pi)