In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook

In [2]:
eth_dfd = pd.read_csv('../Dataset/Binance_ETHUSDT_1h.csv')
eth_dfd

Unix                 Date   Symbol     Open     High      Low  \
0      1672527600000  2022-12-31 23:00:00  ETHUSDT  1196.18  1197.43  1193.60   
1      1672524000000  2022-12-31 22:00:00  ETHUSDT  1200.09  1201.11  1193.08   
2      1672520400000  2022-12-31 21:00:00  ETHUSDT  1202.33  1203.00  1199.83   
3      1672516800000  2022-12-31 20:00:00  ETHUSDT  1202.66  1203.71  1202.30   
4      1672513200000  2022-12-31 19:00:00  ETHUSDT  1199.59  1205.61  1199.42   
...              ...                  ...      ...      ...      ...      ...   
26269  1577851200000  2020-01-01 04:00:00  ETHUSDT   130.21   130.74   130.15   
26270  1577847600000  2020-01-01 03:00:00  ETHUSDT   130.85   130.89   129.94   
26271  1577844000000  2020-01-01 02:00:00  ETHUSDT   130.63   130.98   130.35   
26272  1577840400000  2020-01-01 01:00:00  ETHUSDT   128.87   130.65   128.78   
26273  1577836800000  2020-01-01 00:00:00  ETHUSDT   129.16   129.19   128.68   

         Close   Volume ETH   Volume USDT  tradecount  
0      1196.13   5927.43200  7.086714e+06       11029  
1      1196.19   9549.47930  1.143952e+07       13241  
2      1200.10   3865.48620  4.643401e+06        7913  
3      1202.34   3557.34730  4.278879e+06        7917  
4      1202.65   6435.02040  7.738029e+06        9906  
...        ...          ...           ...         ...  
26269   130.20   3397.90747  4.430067e+05        2264  
26270   130.20   4968.55433  6.473610e+05        2818  
26271   130.85   7603.35623  9.940256e+05        3046  
26272   130.64  11344.65516  1.474278e+06        4885  
26273   128.87   7769.17336  1.000930e+06        2504  

[26274 rows x 10 columns]

In [3]:
df = Preprocessing.feature_selection(eth_dfd)
df

Open     High      Low   Volume USDT    Close
0       129.16   129.19   128.68  1.000930e+06   128.87
1       128.87   130.65   128.78  1.474278e+06   130.64
2       130.63   130.98   130.35  9.940256e+05   130.85
3       130.85   130.89   129.94  6.473610e+05   130.20
4       130.21   130.74   130.15  4.430067e+05   130.20
...        ...      ...      ...           ...      ...
26269  1199.59  1205.61  1199.42  7.738029e+06  1202.65
26270  1202.66  1203.71  1202.30  4.278879e+06  1202.34
26271  1202.33  1203.00  1199.83  4.643401e+06  1200.10
26272  1200.09  1201.11  1193.08  1.143952e+07  1196.19
26273  1196.18  1197.43  1193.60  7.086714e+06  1196.13

[26274 rows x 5 columns]

In [4]:
df_no_dup = Preprocessing.handle_duplicate(df)
df_no_dup

duplicate ok


Open     High      Low   Volume USDT    Close
0       129.16   129.19   128.68  1.000930e+06   128.87
1       128.87   130.65   128.78  1.474278e+06   130.64
2       130.63   130.98   130.35  9.940256e+05   130.85
3       130.85   130.89   129.94  6.473610e+05   130.20
4       130.21   130.74   130.15  4.430067e+05   130.20
...        ...      ...      ...           ...      ...
26269  1199.59  1205.61  1199.42  7.738029e+06  1202.65
26270  1202.66  1203.71  1202.30  4.278879e+06  1202.34
26271  1202.33  1203.00  1199.83  4.643401e+06  1200.10
26272  1200.09  1201.11  1193.08  1.143952e+07  1196.19
26273  1196.18  1197.43  1193.60  7.086714e+06  1196.13

[26274 rows x 5 columns]

In [5]:
miss = Preprocessing.handle_missing_value(df_no_dup)
miss

No missing value


False

In [6]:
x, scaler = Preprocessing.minmax_scale(df_no_dup)
x

array([[0.00687306, 0.00493458, 0.00899058, 0.00085515, 0.00678935],
       [0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
       [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
       ...,
       [0.23278314, 0.23041549, 0.23462933, 0.00396711, 0.23230718],
       [0.2323116 , 0.23001863, 0.23320743, 0.00977339, 0.23148404],
       [0.23148852, 0.22924589, 0.23331697, 0.00605456, 0.2314714 ]])

In [7]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.00687306, 0.00493458, 0.00899058, 0.00085515, 0.00678935],
       [0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
       [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
       ...,
       [0.36569953, 0.36527651, 0.3650033 , 0.03678181, 0.36294049],
       [0.36293557, 0.3619231 , 0.35881859, 0.0818867 , 0.35696376],
       [0.35696347, 0.35758067, 0.3546814 , 0.09563107, 0.35310278]])

In [8]:
test

array([[0.35310067, 0.35162768, 0.34770043, 0.15036013, 0.34664396],
       [0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
       [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
       ...,
       [0.23278314, 0.23041549, 0.23462933, 0.00396711, 0.23230718],
       [0.2323116 , 0.23001863, 0.23320743, 0.00977339, 0.23148404],
       [0.23148852, 0.22924589, 0.23331697, 0.00605456, 0.2314714 ]])

In [9]:
train_X, train_y = Preprocessing.create_dataset(train,5)
test_X, test_y = Preprocessing.create_dataset(test,5)

In [10]:
train_X

array([[[0.00687306, 0.00493458, 0.00899058, 0.00085515, 0.00678935],
        [0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
        [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
        [0.00722882, 0.00529155, 0.009256  , 0.00055308, 0.00706934],
        [0.00709409, 0.00526005, 0.00930024, 0.00037848, 0.00706934]],

       [[0.00681201, 0.00524115, 0.00901165, 0.00125955, 0.00716197],
        [0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
        [0.00722882, 0.00529155, 0.009256  , 0.00055308, 0.00706934],
        [0.00709409, 0.00526005, 0.00930024, 0.00037848, 0.00706934],
        [0.00709199, 0.00520336, 0.00929181, 0.00047243, 0.00709039]],

       [[0.00718251, 0.00531045, 0.00934237, 0.00084925, 0.00720618],
        [0.00722882, 0.00529155, 0.009256  , 0.00055308, 0.00706934],
        [0.00709409, 0.00526005, 0.00930024, 0.00037848, 0.00706934],
        [0.00709199, 0.00520336, 0.00929181, 0.00047243, 0.00709039],
        [0.00711

In [11]:
train_y

array([0.00709039, 0.00711987, 0.00707776, ..., 0.36294049, 0.35696376,
       0.35310278])

In [12]:
test_X

array([[[0.35310067, 0.35162768, 0.34770043, 0.15036013, 0.34664396],
        [0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
        [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.34708184],
        [0.34708226, 0.34721595, 0.34265955, 0.10696327, 0.34520188]],

       [[0.3466423 , 0.3490365 , 0.34609738, 0.1292612 , 0.34877655],
        [0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.34708184],
        [0.34708226, 0.34721595, 0.34265955, 0.10696327, 0.34520188],
        [0.34520033, 0.35104603, 0.3447787 , 0.10501199, 0.35243332]],

       [[0.34877474, 0.35155628, 0.35085387, 0.06693593, 0.35186281],
        [0.35186288, 0.35105233, 0.34876   , 0.06304256, 0.34708184],
        [0.34708226, 0.34721595, 0.34265955, 0.10696327, 0.34520188],
        [0.34520033, 0.35104603, 0.3447787 , 0.10501199, 0.35243332],
        [0.35243

In [13]:
test_y

array([0.35243332, 0.35114703, 0.35150913, ..., 0.23230718, 0.23148404,
       0.2314714 ])

In [14]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(21014, 5, 5) (21014,) (5250, 5, 5) (5250,)


## Model Training

In [15]:
hyperparams = []
batch = [32, 64, 128]
epoch = [100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(32, 100, 50),
 (32, 100, 60),
 (32, 100, 100),
 (64, 100, 50),
 (64, 100, 60),
 (64, 100, 100),
 (128, 100, 50),
 (128, 100, 60),
 (128, 100, 100)]

In [17]:
lstms = []
models = []
for batch, epoch, neuron in hyperparams:
    model, lstm = LSTMUnit.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms.append(lstm)
    models.append(model)

Epoch 1/100


2023-03-21 23:21:26.581972: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:21:26.661262: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:21:26.736462: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:21:31.858576: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:21:31.893402: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 6s - loss: 2.3820e-04 - mse: 2.3820e-04 - val_loss: 4.9260e-04 - val_mse: 4.9260e-04 - 6s/epoch - 10ms/step
Epoch 2/100
657/657 - 5s - loss: 3.0331e-04 - mse: 3.0331e-04 - val_loss: 3.7209e-04 - val_mse: 3.7209e-04 - 5s/epoch - 8ms/step
Epoch 3/100
657/657 - 5s - loss: 4.3592e-04 - mse: 4.3592e-04 - val_loss: 2.7922e-04 - val_mse: 2.7922e-04 - 5s/epoch - 8ms/step
Epoch 4/100
657/657 - 5s - loss: 6.3618e-04 - mse: 6.3618e-04 - val_loss: 6.2076e-04 - val_mse: 6.2076e-04 - 5s/epoch - 8ms/step
Epoch 5/100
657/657 - 5s - loss: 6.7476e-04 - mse: 6.7476e-04 - val_loss: 6.8184e-04 - val_mse: 6.8184e-04 - 5s/epoch - 8ms/step
Epoch 6/100
657/657 - 5s - loss: 5.8816e-04 - mse: 5.8816e-04 - val_loss: 4.7392e-04 - val_mse: 4.7392e-04 - 5s/epoch - 8ms/step
Epoch 7/100
657/657 - 5s - loss: 4.8676e-04 - mse: 4.8676e-04 - val_loss: 2.9414e-04 - val_mse: 2.9414e-04 - 5s/epoch - 8ms/step
Epoch 8/100
657/657 - 5s - loss: 4.0852e-04 - mse: 4.0852e-04 - val_loss: 1.7675e-04 - val_mse: 1.7675e-04 -

2023-03-21 23:30:31.809997: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:30:31.904833: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:30:31.995586: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:30:37.618465: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:30:37.651851: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 7s - loss: 1.4536e-04 - mse: 1.4536e-04 - val_loss: 4.3654e-04 - val_mse: 4.3654e-04 - 7s/epoch - 11ms/step
Epoch 2/100
657/657 - 6s - loss: 1.9731e-04 - mse: 1.9731e-04 - val_loss: 2.6385e-04 - val_mse: 2.6385e-04 - 6s/epoch - 9ms/step
Epoch 3/100
657/657 - 6s - loss: 2.1203e-04 - mse: 2.1203e-04 - val_loss: 2.7800e-04 - val_mse: 2.7800e-04 - 6s/epoch - 9ms/step
Epoch 4/100
657/657 - 6s - loss: 2.9561e-04 - mse: 2.9561e-04 - val_loss: 1.9774e-04 - val_mse: 1.9774e-04 - 6s/epoch - 9ms/step
Epoch 5/100
657/657 - 6s - loss: 5.2397e-04 - mse: 5.2397e-04 - val_loss: 3.2524e-04 - val_mse: 3.2524e-04 - 6s/epoch - 9ms/step
Epoch 6/100
657/657 - 6s - loss: 6.9828e-04 - mse: 6.9828e-04 - val_loss: 6.8021e-04 - val_mse: 6.8021e-04 - 6s/epoch - 9ms/step
Epoch 7/100
657/657 - 6s - loss: 6.4801e-04 - mse: 6.4801e-04 - val_loss: 5.3503e-04 - val_mse: 5.3503e-04 - 6s/epoch - 9ms/step
Epoch 8/100
657/657 - 6s - loss: 5.3689e-04 - mse: 5.3689e-04 - val_loss: 3.3540e-04 - val_mse: 3.3540e-04 -

2023-03-21 23:40:03.980117: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:40:04.081612: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:40:04.188363: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:40:09.691179: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:40:09.728771: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 7s - loss: 1.5754e-04 - mse: 1.5754e-04 - val_loss: 5.7495e-04 - val_mse: 5.7495e-04 - 7s/epoch - 11ms/step
Epoch 2/100
657/657 - 6s - loss: 2.0483e-04 - mse: 2.0483e-04 - val_loss: 3.7149e-04 - val_mse: 3.7149e-04 - 6s/epoch - 9ms/step
Epoch 3/100
657/657 - 6s - loss: 1.7823e-04 - mse: 1.7823e-04 - val_loss: 2.4584e-04 - val_mse: 2.4584e-04 - 6s/epoch - 9ms/step
Epoch 4/100
657/657 - 6s - loss: 1.9116e-04 - mse: 1.9116e-04 - val_loss: 2.6153e-04 - val_mse: 2.6153e-04 - 6s/epoch - 9ms/step
Epoch 5/100
657/657 - 6s - loss: 2.3603e-04 - mse: 2.3603e-04 - val_loss: 2.3132e-04 - val_mse: 2.3132e-04 - 6s/epoch - 9ms/step
Epoch 6/100
657/657 - 6s - loss: 4.0356e-04 - mse: 4.0356e-04 - val_loss: 1.7564e-04 - val_mse: 1.7564e-04 - 6s/epoch - 9ms/step
Epoch 7/100
657/657 - 6s - loss: 7.4923e-04 - mse: 7.4923e-04 - val_loss: 6.6063e-04 - val_mse: 6.6063e-04 - 6s/epoch - 9ms/step
Epoch 8/100
657/657 - 7s - loss: 8.1004e-04 - mse: 8.1004e-04 - val_loss: 7.5932e-04 - val_mse: 7.5932e-04 -

2023-03-21 23:50:06.330803: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:50:06.433356: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:50:06.538239: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:50:09.639255: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:50:09.676130: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 4s - loss: 5.2995e-04 - mse: 5.2995e-04 - val_loss: 8.9298e-04 - val_mse: 8.9298e-04 - 4s/epoch - 13ms/step
Epoch 2/100
329/329 - 3s - loss: 5.4474e-04 - mse: 5.4474e-04 - val_loss: 4.7399e-04 - val_mse: 4.7399e-04 - 3s/epoch - 9ms/step
Epoch 3/100
329/329 - 3s - loss: 3.9793e-04 - mse: 3.9793e-04 - val_loss: 3.2215e-04 - val_mse: 3.2215e-04 - 3s/epoch - 9ms/step
Epoch 4/100
329/329 - 3s - loss: 3.1989e-04 - mse: 3.1989e-04 - val_loss: 2.2574e-04 - val_mse: 2.2574e-04 - 3s/epoch - 9ms/step
Epoch 5/100
329/329 - 3s - loss: 2.7105e-04 - mse: 2.7105e-04 - val_loss: 1.6741e-04 - val_mse: 1.6741e-04 - 3s/epoch - 9ms/step
Epoch 6/100
329/329 - 3s - loss: 2.3333e-04 - mse: 2.3333e-04 - val_loss: 1.2787e-04 - val_mse: 1.2787e-04 - 3s/epoch - 9ms/step
Epoch 7/100
329/329 - 3s - loss: 2.0254e-04 - mse: 2.0254e-04 - val_loss: 1.0109e-04 - val_mse: 1.0109e-04 - 3s/epoch - 9ms/step
Epoch 8/100
329/329 - 3s - loss: 1.7732e-04 - mse: 1.7732e-04 - val_loss: 8.2708e-05 - val_mse: 8.2708e-05 -

2023-03-21 23:55:15.171519: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:55:15.281780: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:55:15.562576: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:55:18.690199: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:55:18.729375: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 4s - loss: 1.4073e-04 - mse: 1.4073e-04 - val_loss: 1.1392e-04 - val_mse: 1.1392e-04 - 4s/epoch - 14ms/step
Epoch 2/100
329/329 - 3s - loss: 2.2847e-04 - mse: 2.2847e-04 - val_loss: 8.3456e-05 - val_mse: 8.3456e-05 - 3s/epoch - 10ms/step
Epoch 3/100
329/329 - 3s - loss: 3.8682e-04 - mse: 3.8682e-04 - val_loss: 6.9093e-04 - val_mse: 6.9093e-04 - 3s/epoch - 10ms/step
Epoch 4/100
329/329 - 3s - loss: 3.4323e-04 - mse: 3.4323e-04 - val_loss: 4.3387e-04 - val_mse: 4.3387e-04 - 3s/epoch - 10ms/step
Epoch 5/100
329/329 - 3s - loss: 2.4884e-04 - mse: 2.4884e-04 - val_loss: 2.6582e-04 - val_mse: 2.6582e-04 - 3s/epoch - 10ms/step
Epoch 6/100
329/329 - 3s - loss: 1.8345e-04 - mse: 1.8345e-04 - val_loss: 1.7111e-04 - val_mse: 1.7111e-04 - 3s/epoch - 9ms/step
Epoch 7/100
329/329 - 3s - loss: 1.5531e-04 - mse: 1.5531e-04 - val_loss: 1.1732e-04 - val_mse: 1.1732e-04 - 3s/epoch - 9ms/step
Epoch 8/100
329/329 - 3s - loss: 1.4305e-04 - mse: 1.4305e-04 - val_loss: 9.2705e-05 - val_mse: 9.2705e-

2023-03-22 00:00:28.023020: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:00:28.127237: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:00:28.462297: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:00:31.618382: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:00:31.656338: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 5s - loss: 2.5156e-04 - mse: 2.5156e-04 - val_loss: 2.5287e-04 - val_mse: 2.5287e-04 - 5s/epoch - 14ms/step
Epoch 2/100
329/329 - 3s - loss: 5.9930e-04 - mse: 5.9930e-04 - val_loss: 0.0011 - val_mse: 0.0011 - 3s/epoch - 10ms/step
Epoch 3/100
329/329 - 3s - loss: 5.7492e-04 - mse: 5.7492e-04 - val_loss: 5.6198e-04 - val_mse: 5.6198e-04 - 3s/epoch - 10ms/step
Epoch 4/100
329/329 - 3s - loss: 3.9451e-04 - mse: 3.9451e-04 - val_loss: 3.4067e-04 - val_mse: 3.4067e-04 - 3s/epoch - 10ms/step
Epoch 5/100
329/329 - 3s - loss: 2.8153e-04 - mse: 2.8153e-04 - val_loss: 2.3212e-04 - val_mse: 2.3212e-04 - 3s/epoch - 10ms/step
Epoch 6/100
329/329 - 3s - loss: 2.2186e-04 - mse: 2.2186e-04 - val_loss: 1.6632e-04 - val_mse: 1.6632e-04 - 3s/epoch - 10ms/step
Epoch 7/100
329/329 - 3s - loss: 1.8398e-04 - mse: 1.8398e-04 - val_loss: 1.2035e-04 - val_mse: 1.2035e-04 - 3s/epoch - 10ms/step
Epoch 8/100
329/329 - 3s - loss: 1.6178e-04 - mse: 1.6178e-04 - val_loss: 9.1492e-05 - val_mse: 9.1492e-05 - 3

2023-03-22 00:05:47.951754: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:05:48.057832: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:05:48.262739: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:05:50.136358: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:05:50.173421: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 3s - loss: 3.7308e-04 - mse: 3.7308e-04 - val_loss: 1.8701e-04 - val_mse: 1.8701e-04 - 3s/epoch - 20ms/step
Epoch 2/100
165/165 - 2s - loss: 9.7860e-04 - mse: 9.7860e-04 - val_loss: 0.0015 - val_mse: 0.0015 - 2s/epoch - 10ms/step
Epoch 3/100
165/165 - 2s - loss: 9.7009e-04 - mse: 9.7009e-04 - val_loss: 8.8718e-04 - val_mse: 8.8718e-04 - 2s/epoch - 10ms/step
Epoch 4/100
165/165 - 2s - loss: 7.0068e-04 - mse: 7.0068e-04 - val_loss: 7.1795e-04 - val_mse: 7.1795e-04 - 2s/epoch - 10ms/step
Epoch 5/100
165/165 - 2s - loss: 5.6113e-04 - mse: 5.6113e-04 - val_loss: 5.3448e-04 - val_mse: 5.3448e-04 - 2s/epoch - 10ms/step
Epoch 6/100
165/165 - 2s - loss: 4.5520e-04 - mse: 4.5520e-04 - val_loss: 3.8417e-04 - val_mse: 3.8417e-04 - 2s/epoch - 10ms/step
Epoch 7/100
165/165 - 2s - loss: 3.7199e-04 - mse: 3.7199e-04 - val_loss: 2.7392e-04 - val_mse: 2.7392e-04 - 2s/epoch - 10ms/step
Epoch 8/100
165/165 - 2s - loss: 3.0418e-04 - mse: 3.0418e-04 - val_loss: 1.9498e-04 - val_mse: 1.9498e-04 - 2

2023-03-22 00:08:30.878029: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:08:30.980769: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:08:31.149950: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:08:32.960731: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:08:32.997513: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 3s - loss: 1.9925e-04 - mse: 1.9925e-04 - val_loss: 4.5058e-05 - val_mse: 4.5058e-05 - 3s/epoch - 18ms/step
Epoch 2/100
165/165 - 2s - loss: 1.5137e-04 - mse: 1.5137e-04 - val_loss: 5.3204e-05 - val_mse: 5.3204e-05 - 2s/epoch - 10ms/step
Epoch 3/100
165/165 - 2s - loss: 1.9058e-04 - mse: 1.9058e-04 - val_loss: 7.6906e-05 - val_mse: 7.6906e-05 - 2s/epoch - 9ms/step
Epoch 4/100
165/165 - 2s - loss: 4.3997e-04 - mse: 4.3997e-04 - val_loss: 5.6058e-04 - val_mse: 5.6058e-04 - 2s/epoch - 10ms/step
Epoch 5/100
165/165 - 2s - loss: 0.0017 - mse: 0.0017 - val_loss: 0.0030 - val_mse: 0.0030 - 2s/epoch - 9ms/step
Epoch 6/100
165/165 - 2s - loss: 0.0013 - mse: 0.0013 - val_loss: 0.0029 - val_mse: 0.0029 - 2s/epoch - 9ms/step
Epoch 7/100
165/165 - 2s - loss: 8.3324e-04 - mse: 8.3324e-04 - val_loss: 0.0015 - val_mse: 0.0015 - 2s/epoch - 9ms/step
Epoch 8/100
165/165 - 2s - loss: 4.7518e-04 - mse: 4.7518e-04 - val_loss: 5.9048e-04 - val_mse: 5.9048e-04 - 2s/epoch - 9ms/step
Epoch 9/100
165/1

2023-03-22 00:11:10.381081: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:11:10.490593: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:11:10.636846: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:11:12.574252: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:11:12.613072: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 3s - loss: 2.6855e-04 - mse: 2.6855e-04 - val_loss: 6.4629e-05 - val_mse: 6.4629e-05 - 3s/epoch - 19ms/step
Epoch 2/100
165/165 - 2s - loss: 2.1828e-04 - mse: 2.1828e-04 - val_loss: 8.3743e-05 - val_mse: 8.3743e-05 - 2s/epoch - 12ms/step
Epoch 3/100
165/165 - 2s - loss: 3.3910e-04 - mse: 3.3910e-04 - val_loss: 1.9779e-04 - val_mse: 1.9779e-04 - 2s/epoch - 11ms/step
Epoch 4/100
165/165 - 2s - loss: 0.0011 - mse: 0.0011 - val_loss: 0.0014 - val_mse: 0.0014 - 2s/epoch - 11ms/step
Epoch 5/100
165/165 - 2s - loss: 0.0027 - mse: 0.0027 - val_loss: 0.0056 - val_mse: 0.0056 - 2s/epoch - 11ms/step
Epoch 6/100
165/165 - 2s - loss: 0.0018 - mse: 0.0018 - val_loss: 0.0044 - val_mse: 0.0044 - 2s/epoch - 10ms/step
Epoch 7/100
165/165 - 2s - loss: 9.5130e-04 - mse: 9.5130e-04 - val_loss: 0.0016 - val_mse: 0.0016 - 2s/epoch - 11ms/step
Epoch 8/100
165/165 - 2s - loss: 4.4285e-04 - mse: 4.4285e-04 - val_loss: 5.3369e-04 - val_mse: 5.3369e-04 - 2s/epoch - 11ms/step
Epoch 9/100
165/165 - 2s - l

In [18]:
import pickle
i=0
for m in models:
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(lstms[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].units))
    print(Evaluation.mape(inv_y,inv_yhat)[0])
    with open('LSTM_ETH'+str(hyperparams[i])+'.pkl', 'wb') as f:
        pickle.dump(lstms[i].history, f)
    i = i+1

 37/165 [=====>........................] - ETA: 0s

2023-03-22 00:13:49.671610: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:49.697761: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(32, 100, 50)
Epoch: 100
Neurons: 50
0.7681451930855532
 12/165 [=>............................] - ETA: 0s 

2023-03-22 00:13:50.373489: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:50.403686: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(32, 100, 60)
Epoch: 100
Neurons: 60
0.761563408229922
 39/165 [======>.......................] - ETA: 0s

2023-03-22 00:13:51.063694: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:51.088577: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 2ms/step
(32, 100, 100)
Epoch: 100
Neurons: 100
0.7701559809091089
 36/165 [=====>........................] - ETA: 0s

2023-03-22 00:13:51.671344: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:51.695934: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(64, 100, 50)
Epoch: 100
Neurons: 50
2.6893279564359514
 35/165 [=====>........................] - ETA: 0s

2023-03-22 00:13:52.296236: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:52.320956: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(64, 100, 60)
Epoch: 100
Neurons: 60
2.8928645728440534
 38/165 [=====>........................] - ETA: 0s

2023-03-22 00:13:52.918742: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:52.942766: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 2ms/step
(64, 100, 100)
Epoch: 100
Neurons: 100
3.2716484747051235
 36/165 [=====>........................] - ETA: 0s

2023-03-22 00:13:53.520394: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:53.544698: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(128, 100, 50)
Epoch: 100
Neurons: 50
1.4255456501292212
 35/165 [=====>........................] - ETA: 0s

2023-03-22 00:13:54.141965: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:54.168861: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(128, 100, 60)
Epoch: 100
Neurons: 60
0.9272444980080943
 38/165 [=====>........................] - ETA: 0s

2023-03-22 00:13:54.769039: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-22 00:13:54.793380: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 2ms/step
(128, 100, 100)
Epoch: 100
Neurons: 100
1.0445642621643774


In [19]:
with open('LSTM_ETH(32, 100, 50).pkl', "rb") as file_pi:
    history = pickle.load(file_pi)