In [1]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook

In [2]:
btc_dfd = pd.read_csv('../Dataset/Binance_BTCUSDT_1h.csv')
btc_dfd

Unix                 Date   Symbol      Open      High  \
0      1672527600000  2022-12-31 23:00:00  BTCUSDT  16520.28  16551.24   
1      1672524000000  2022-12-31 22:00:00  BTCUSDT  16548.28  16567.49   
2      1672520400000  2022-12-31 21:00:00  BTCUSDT  16568.19  16571.64   
3      1672516800000  2022-12-31 20:00:00  BTCUSDT  16570.14  16574.97   
4      1672513200000  2022-12-31 19:00:00  BTCUSDT  16577.78  16590.06   
...              ...                  ...      ...       ...       ...   
26269  1577851200000  2020-01-01 04:00:00  BTCUSDT   7225.00   7230.00   
26270  1577847600000  2020-01-01 03:00:00  BTCUSDT   7242.66   7245.00   
26271  1577844000000  2020-01-01 02:00:00  BTCUSDT   7215.52   7244.87   
26272  1577840400000  2020-01-01 01:00:00  BTCUSDT   7176.47   7230.00   
26273  1577836800000  2020-01-01 00:00:00  BTCUSDT   7195.24   7196.25   

            Low     Close   Volume BTC   Volume USDT  tradecount  
0      16487.74  16542.40  4973.433070  8.217183e+07      152632  
1      16470.00  16520.81  6695.136250  1.106669e+08      153933  
2      16544.12  16548.28  3618.773890  5.992803e+07      105065  
3      16564.09  16568.60  2622.143550  4.344849e+07       90705  
4      16565.10  16570.14  4044.433590  6.704605e+07      116587  
...         ...       ...          ...           ...         ...  
26269   7215.03   7217.27   467.812578  3.379094e+06        5896  
26270   7220.00   7225.01   783.724867  5.667367e+06        8337  
26271   7211.41   7242.85   655.156809  4.736719e+06        7466  
26272   7175.71   7216.27   883.052603  6.365953e+06        9033  
26273   7175.46   7177.02   511.814901  3.675857e+06        7640  

[26274 rows x 10 columns]

In [3]:
df = Preprocessing.feature_selection(btc_dfd)
df

Open      High       Low   Volume USDT     Close
0       7195.24   7196.25   7175.46  3.675857e+06   7177.02
1       7176.47   7230.00   7175.71  6.365953e+06   7216.27
2       7215.52   7244.87   7211.41  4.736719e+06   7242.85
3       7242.66   7245.00   7220.00  5.667367e+06   7225.01
4       7225.00   7230.00   7215.03  3.379094e+06   7217.27
...         ...       ...       ...           ...       ...
26269  16577.78  16590.06  16565.10  6.704605e+07  16570.14
26270  16570.14  16574.97  16564.09  4.344849e+07  16568.60
26271  16568.19  16571.64  16544.12  5.992803e+07  16548.28
26272  16548.28  16567.49  16470.00  1.106669e+08  16520.81
26273  16520.28  16551.24  16487.74  8.217183e+07  16542.40

[26274 rows x 5 columns]

In [4]:
df_no_dup = Preprocessing.handle_duplicate(df)
df_no_dup

duplicate ok


Open      High       Low   Volume USDT     Close
0       7195.24   7196.25   7175.46  3.675857e+06   7177.02
1       7176.47   7230.00   7175.71  6.365953e+06   7216.27
2       7215.52   7244.87   7211.41  4.736719e+06   7242.85
3       7242.66   7245.00   7220.00  5.667367e+06   7225.01
4       7225.00   7230.00   7215.03  3.379094e+06   7217.27
...         ...       ...       ...           ...       ...
26269  16577.78  16590.06  16565.10  6.704605e+07  16570.14
26270  16570.14  16574.97  16564.09  4.344849e+07  16568.60
26271  16568.19  16571.64  16544.12  5.992803e+07  16548.28
26272  16548.28  16567.49  16470.00  1.106669e+08  16520.81
26273  16520.28  16551.24  16487.74  8.217183e+07  16542.40

[26274 rows x 5 columns]

In [5]:
miss = Preprocessing.handle_missing_value(df_no_dup)
miss

No missing value


False

In [6]:
x, scaler = Preprocessing.minmax_scale(df_no_dup)
x

array([[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
       [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
       [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
       ...,
       [0.19280946, 0.1857686 , 0.19734306, 0.01993857, 0.19251245],
       [0.19250079, 0.18570415, 0.19619691, 0.03681983, 0.19208658],
       [0.19206671, 0.18545178, 0.19647123, 0.02733927, 0.19242129]])

In [7]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
       [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
       [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
       ...,
       [0.39451404, 0.38918512, 0.39751838, 0.01247029, 0.39344233],
       [0.39342821, 0.38742771, 0.39264325, 0.02946575, 0.3886748 ],
       [0.38866059, 0.38484765, 0.39034385, 0.03564371, 0.38670838]])

In [8]:
test

array([[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
       [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
       [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
       ...,
       [0.19280946, 0.1857686 , 0.19734306, 0.01993857, 0.19251245],
       [0.19250079, 0.18570415, 0.19619691, 0.03681983, 0.19208658],
       [0.19206671, 0.18545178, 0.19647123, 0.02733927, 0.19242129]])

In [9]:
train_X, train_y = Preprocessing.create_dataset(train,5)
test_X, test_y = Preprocessing.create_dataset(test,5)

In [10]:
train_X

array([[[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
        [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
        [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.04797246],
        [0.04796253, 0.04068955, 0.05308412, 0.00112425, 0.04785247]],

       [[0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
        [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.04797246],
        [0.04796253, 0.04068955, 0.05308412, 0.00112425, 0.04785247],
        [0.04784254, 0.04068582, 0.05310917, 0.00082828, 0.04796006]],

       [[0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.04797246],
        [0.04796253, 0.04068955, 0.05308412, 0.00112425, 0.04785247],
        [0.04784254, 0.04068582, 0.05310917, 0.00082828, 0.04796006],
        [0.04795

In [11]:
train_y

array([0.04796006, 0.04798192, 0.04773712, ..., 0.39344233, 0.3886748 ,
       0.38670838])

In [12]:
test_X

array([[[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
        [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.38442601],
        [0.38441201, 0.37958689, 0.38444598, 0.06968765, 0.38245246]],

       [[0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.38442601],
        [0.38441201, 0.37958689, 0.38444598, 0.06968765, 0.38245246],
        [0.38243833, 0.37939121, 0.38454046, 0.07592605, 0.38515838]],

       [[0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.38442601],
        [0.38441201, 0.37958689, 0.38444598, 0.06968765, 0.38245246],
        [0.38243833, 0.37939121, 0.38454046, 0.07592605, 0.38515838],
        [0.38514

In [13]:
test_y

array([0.38515838, 0.38544456, 0.38463778, ..., 0.19251245, 0.19208658,
       0.19242129])

In [14]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(21014, 5, 5) (21014,) (5250, 5, 5) (5250,)


## Model Training

In [15]:
hyperparams = []
batch = [32, 64, 128]
epoch = [100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(32, 100, 50),
 (32, 100, 60),
 (32, 100, 100),
 (64, 100, 50),
 (64, 100, 60),
 (64, 100, 100),
 (128, 100, 50),
 (128, 100, 60),
 (128, 100, 100)]

In [16]:
lstms = []
models = []
for batch, epoch, neuron in hyperparams:
    model, lstm = LSTMUnit.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms.append(lstm)
    models.append(model)

Metal device set to: Apple M1


2023-03-21 22:28:08.197247: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-21 22:28:08.197618: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Epoch 1/100


2023-03-21 22:28:08.448163: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-03-21 22:28:08.839455: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:28:08.924000: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:28:09.045648: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:28:13.547994: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:28:13.577109: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 6s - loss: 2.4701e-04 - mse: 2.4701e-04 - val_loss: 7.0376e-04 - val_mse: 7.0376e-04 - 6s/epoch - 9ms/step
Epoch 2/100
657/657 - 5s - loss: 2.1877e-04 - mse: 2.1877e-04 - val_loss: 5.0941e-04 - val_mse: 5.0941e-04 - 5s/epoch - 7ms/step
Epoch 3/100
657/657 - 5s - loss: 3.1639e-04 - mse: 3.1639e-04 - val_loss: 2.5595e-04 - val_mse: 2.5595e-04 - 5s/epoch - 8ms/step
Epoch 4/100
657/657 - 5s - loss: 4.5288e-04 - mse: 4.5288e-04 - val_loss: 3.5272e-04 - val_mse: 3.5272e-04 - 5s/epoch - 7ms/step
Epoch 5/100
657/657 - 5s - loss: 8.6469e-04 - mse: 8.6469e-04 - val_loss: 8.5789e-04 - val_mse: 8.5789e-04 - 5s/epoch - 7ms/step
Epoch 6/100
657/657 - 5s - loss: 7.5457e-04 - mse: 7.5457e-04 - val_loss: 5.8982e-04 - val_mse: 5.8982e-04 - 5s/epoch - 7ms/step
Epoch 7/100
657/657 - 5s - loss: 6.0858e-04 - mse: 6.0858e-04 - val_loss: 3.2734e-04 - val_mse: 3.2734e-04 - 5s/epoch - 7ms/step
Epoch 8/100
657/657 - 5s - loss: 4.9642e-04 - mse: 4.9642e-04 - val_loss: 1.6305e-04 - val_mse: 1.6305e-04 - 

2023-03-21 22:36:04.088498: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:36:04.170515: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:36:04.245412: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:36:08.686014: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:36:08.716637: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 6s - loss: 1.9122e-04 - mse: 1.9122e-04 - val_loss: 7.3634e-04 - val_mse: 7.3634e-04 - 6s/epoch - 9ms/step
Epoch 2/100
657/657 - 5s - loss: 1.9645e-04 - mse: 1.9645e-04 - val_loss: 4.4058e-04 - val_mse: 4.4058e-04 - 5s/epoch - 7ms/step
Epoch 3/100
657/657 - 5s - loss: 2.3405e-04 - mse: 2.3405e-04 - val_loss: 5.1055e-04 - val_mse: 5.1055e-04 - 5s/epoch - 8ms/step
Epoch 4/100
657/657 - 5s - loss: 3.5430e-04 - mse: 3.5430e-04 - val_loss: 2.5521e-04 - val_mse: 2.5521e-04 - 5s/epoch - 7ms/step
Epoch 5/100
657/657 - 5s - loss: 5.5366e-04 - mse: 5.5366e-04 - val_loss: 5.9267e-04 - val_mse: 5.9267e-04 - 5s/epoch - 7ms/step
Epoch 6/100
657/657 - 5s - loss: 8.8797e-04 - mse: 8.8797e-04 - val_loss: 0.0010 - val_mse: 0.0010 - 5s/epoch - 7ms/step
Epoch 7/100
657/657 - 5s - loss: 7.3451e-04 - mse: 7.3451e-04 - val_loss: 6.7886e-04 - val_mse: 6.7886e-04 - 5s/epoch - 7ms/step
Epoch 8/100
657/657 - 5s - loss: 5.9198e-04 - mse: 5.9198e-04 - val_loss: 3.8749e-04 - val_mse: 3.8749e-04 - 5s/epoch

2023-03-21 22:43:57.341735: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:43:57.420559: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:43:57.495651: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:44:01.787478: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:44:01.816834: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


657/657 - 5s - loss: 2.1468e-04 - mse: 2.1468e-04 - val_loss: 0.0012 - val_mse: 0.0012 - 5s/epoch - 8ms/step
Epoch 2/100
657/657 - 5s - loss: 2.5820e-04 - mse: 2.5820e-04 - val_loss: 9.1164e-04 - val_mse: 9.1164e-04 - 5s/epoch - 7ms/step
Epoch 3/100
657/657 - 5s - loss: 2.5331e-04 - mse: 2.5331e-04 - val_loss: 6.4991e-04 - val_mse: 6.4991e-04 - 5s/epoch - 7ms/step
Epoch 4/100
657/657 - 5s - loss: 3.7350e-04 - mse: 3.7350e-04 - val_loss: 3.5289e-04 - val_mse: 3.5289e-04 - 5s/epoch - 7ms/step
Epoch 5/100
657/657 - 5s - loss: 5.1160e-04 - mse: 5.1160e-04 - val_loss: 4.9403e-04 - val_mse: 4.9403e-04 - 5s/epoch - 7ms/step
Epoch 6/100
657/657 - 5s - loss: 9.7154e-04 - mse: 9.7154e-04 - val_loss: 0.0014 - val_mse: 0.0014 - 5s/epoch - 7ms/step
Epoch 7/100
657/657 - 5s - loss: 9.9477e-04 - mse: 9.9477e-04 - val_loss: 0.0012 - val_mse: 0.0012 - 5s/epoch - 7ms/step
Epoch 8/100
657/657 - 5s - loss: 8.4935e-04 - mse: 8.4935e-04 - val_loss: 7.6639e-04 - val_mse: 7.6639e-04 - 5s/epoch - 7ms/step
Epoc

2023-03-21 22:51:43.915507: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:51:44.002009: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:51:44.096945: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:51:46.471633: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:51:46.501206: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 3s - loss: 6.4716e-04 - mse: 6.4716e-04 - val_loss: 6.8704e-04 - val_mse: 6.8704e-04 - 3s/epoch - 10ms/step
Epoch 2/100
329/329 - 2s - loss: 5.0601e-04 - mse: 5.0601e-04 - val_loss: 3.5027e-04 - val_mse: 3.5027e-04 - 2s/epoch - 7ms/step
Epoch 3/100
329/329 - 2s - loss: 3.4350e-04 - mse: 3.4350e-04 - val_loss: 1.9458e-04 - val_mse: 1.9458e-04 - 2s/epoch - 7ms/step
Epoch 4/100
329/329 - 2s - loss: 2.5659e-04 - mse: 2.5659e-04 - val_loss: 1.1316e-04 - val_mse: 1.1316e-04 - 2s/epoch - 7ms/step
Epoch 5/100
329/329 - 2s - loss: 1.8958e-04 - mse: 1.8958e-04 - val_loss: 7.3991e-05 - val_mse: 7.3991e-05 - 2s/epoch - 7ms/step
Epoch 6/100
329/329 - 2s - loss: 1.4188e-04 - mse: 1.4188e-04 - val_loss: 4.7008e-05 - val_mse: 4.7008e-05 - 2s/epoch - 8ms/step
Epoch 7/100
329/329 - 3s - loss: 1.1532e-04 - mse: 1.1532e-04 - val_loss: 2.4010e-05 - val_mse: 2.4010e-05 - 3s/epoch - 8ms/step
Epoch 8/100
329/329 - 2s - loss: 1.0514e-04 - mse: 1.0514e-04 - val_loss: 1.3704e-05 - val_mse: 1.3704e-05 -

2023-03-21 22:55:49.578502: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:55:49.691952: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:55:49.785203: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:55:52.344492: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:55:52.374130: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 4s - loss: 2.2065e-04 - mse: 2.2065e-04 - val_loss: 2.2069e-04 - val_mse: 2.2069e-04 - 4s/epoch - 11ms/step
Epoch 2/100
329/329 - 3s - loss: 4.9088e-04 - mse: 4.9088e-04 - val_loss: 4.2985e-04 - val_mse: 4.2985e-04 - 3s/epoch - 8ms/step
Epoch 3/100
329/329 - 2s - loss: 2.5761e-04 - mse: 2.5761e-04 - val_loss: 2.1679e-04 - val_mse: 2.1679e-04 - 2s/epoch - 7ms/step
Epoch 4/100
329/329 - 2s - loss: 1.7109e-04 - mse: 1.7109e-04 - val_loss: 9.8809e-05 - val_mse: 9.8809e-05 - 2s/epoch - 7ms/step
Epoch 5/100
329/329 - 2s - loss: 1.3257e-04 - mse: 1.3257e-04 - val_loss: 3.8279e-05 - val_mse: 3.8279e-05 - 2s/epoch - 7ms/step
Epoch 6/100
329/329 - 3s - loss: 1.1760e-04 - mse: 1.1760e-04 - val_loss: 1.8409e-05 - val_mse: 1.8409e-05 - 3s/epoch - 8ms/step
Epoch 7/100
329/329 - 3s - loss: 1.1177e-04 - mse: 1.1177e-04 - val_loss: 1.4014e-05 - val_mse: 1.4014e-05 - 3s/epoch - 8ms/step
Epoch 8/100
329/329 - 2s - loss: 1.1081e-04 - mse: 1.1081e-04 - val_loss: 1.4522e-05 - val_mse: 1.4522e-05 -

2023-03-21 22:59:58.895242: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:59:58.978213: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 22:59:59.064205: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:00:01.552006: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:00:01.582163: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


329/329 - 3s - loss: 2.1142e-04 - mse: 2.1142e-04 - val_loss: 2.0828e-04 - val_mse: 2.0828e-04 - 3s/epoch - 10ms/step
Epoch 2/100
329/329 - 3s - loss: 2.6839e-04 - mse: 2.6839e-04 - val_loss: 3.6347e-04 - val_mse: 3.6347e-04 - 3s/epoch - 8ms/step
Epoch 3/100
329/329 - 3s - loss: 6.9006e-04 - mse: 6.9006e-04 - val_loss: 5.8208e-04 - val_mse: 5.8208e-04 - 3s/epoch - 8ms/step
Epoch 4/100
329/329 - 3s - loss: 4.1393e-04 - mse: 4.1393e-04 - val_loss: 3.1731e-04 - val_mse: 3.1731e-04 - 3s/epoch - 8ms/step
Epoch 5/100
329/329 - 3s - loss: 2.9018e-04 - mse: 2.9018e-04 - val_loss: 2.0035e-04 - val_mse: 2.0035e-04 - 3s/epoch - 8ms/step
Epoch 6/100
329/329 - 3s - loss: 2.1229e-04 - mse: 2.1229e-04 - val_loss: 1.3060e-04 - val_mse: 1.3060e-04 - 3s/epoch - 8ms/step
Epoch 7/100
329/329 - 3s - loss: 1.5998e-04 - mse: 1.5998e-04 - val_loss: 7.6692e-05 - val_mse: 7.6692e-05 - 3s/epoch - 8ms/step
Epoch 8/100
329/329 - 3s - loss: 1.3097e-04 - mse: 1.3097e-04 - val_loss: 3.8363e-05 - val_mse: 3.8363e-05 -

2023-03-21 23:04:11.457053: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:04:11.535185: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:04:11.640577: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:04:13.012743: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:04:13.042204: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 2s - loss: 4.9571e-04 - mse: 4.9571e-04 - val_loss: 2.2996e-04 - val_mse: 2.2996e-04 - 2s/epoch - 13ms/step
Epoch 2/100
165/165 - 1s - loss: 2.3130e-04 - mse: 2.3130e-04 - val_loss: 2.7601e-04 - val_mse: 2.7601e-04 - 1s/epoch - 8ms/step
Epoch 3/100
165/165 - 1s - loss: 2.9836e-04 - mse: 2.9836e-04 - val_loss: 5.7345e-04 - val_mse: 5.7345e-04 - 1s/epoch - 8ms/step
Epoch 4/100
165/165 - 1s - loss: 5.9409e-04 - mse: 5.9409e-04 - val_loss: 9.6544e-04 - val_mse: 9.6544e-04 - 1s/epoch - 8ms/step
Epoch 5/100
165/165 - 1s - loss: 0.0012 - mse: 0.0012 - val_loss: 0.0035 - val_mse: 0.0035 - 1s/epoch - 8ms/step
Epoch 6/100
165/165 - 1s - loss: 0.0018 - mse: 0.0018 - val_loss: 0.0059 - val_mse: 0.0059 - 1s/epoch - 8ms/step
Epoch 7/100
165/165 - 1s - loss: 0.0022 - mse: 0.0022 - val_loss: 0.0088 - val_mse: 0.0088 - 1s/epoch - 8ms/step
Epoch 8/100
165/165 - 1s - loss: 0.0026 - mse: 0.0026 - val_loss: 0.0103 - val_mse: 0.0103 - 1s/epoch - 8ms/step
Epoch 9/100
165/165 - 1s - loss: 0.0033 - m

2023-03-21 23:06:24.445465: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:06:24.536887: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:06:24.623669: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:06:26.018223: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:06:26.048300: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 2s - loss: 4.0521e-04 - mse: 4.0521e-04 - val_loss: 2.4107e-04 - val_mse: 2.4107e-04 - 2s/epoch - 14ms/step
Epoch 2/100
165/165 - 1s - loss: 2.2371e-04 - mse: 2.2371e-04 - val_loss: 3.0305e-04 - val_mse: 3.0305e-04 - 1s/epoch - 8ms/step
Epoch 3/100
165/165 - 1s - loss: 3.0193e-04 - mse: 3.0193e-04 - val_loss: 5.6998e-04 - val_mse: 5.6998e-04 - 1s/epoch - 8ms/step
Epoch 4/100
165/165 - 1s - loss: 5.6604e-04 - mse: 5.6604e-04 - val_loss: 8.5723e-04 - val_mse: 8.5723e-04 - 1s/epoch - 8ms/step
Epoch 5/100
165/165 - 1s - loss: 0.0010 - mse: 0.0010 - val_loss: 0.0031 - val_mse: 0.0031 - 1s/epoch - 8ms/step
Epoch 6/100
165/165 - 1s - loss: 0.0014 - mse: 0.0014 - val_loss: 0.0036 - val_mse: 0.0036 - 1s/epoch - 8ms/step
Epoch 7/100
165/165 - 1s - loss: 0.0017 - mse: 0.0017 - val_loss: 0.0060 - val_mse: 0.0060 - 1s/epoch - 7ms/step
Epoch 8/100
165/165 - 1s - loss: 0.0019 - mse: 0.0019 - val_loss: 0.0078 - val_mse: 0.0078 - 1s/epoch - 7ms/step
Epoch 9/100
165/165 - 1s - loss: 0.0022 - m

2023-03-21 23:08:28.210347: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:08:28.293985: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:08:28.401855: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:08:29.892989: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:08:29.922610: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 - 2s - loss: 4.7797e-04 - mse: 4.7797e-04 - val_loss: 3.9250e-04 - val_mse: 3.9250e-04 - 2s/epoch - 14ms/step
Epoch 2/100
165/165 - 1s - loss: 3.0428e-04 - mse: 3.0428e-04 - val_loss: 5.7546e-04 - val_mse: 5.7546e-04 - 1s/epoch - 8ms/step
Epoch 3/100
165/165 - 1s - loss: 4.8930e-04 - mse: 4.8930e-04 - val_loss: 8.3296e-04 - val_mse: 8.3296e-04 - 1s/epoch - 8ms/step
Epoch 4/100
165/165 - 1s - loss: 0.0011 - mse: 0.0011 - val_loss: 0.0031 - val_mse: 0.0031 - 1s/epoch - 8ms/step
Epoch 5/100
165/165 - 1s - loss: 0.0016 - mse: 0.0016 - val_loss: 0.0039 - val_mse: 0.0039 - 1s/epoch - 8ms/step
Epoch 6/100
165/165 - 1s - loss: 0.0018 - mse: 0.0018 - val_loss: 0.0054 - val_mse: 0.0054 - 1s/epoch - 8ms/step
Epoch 7/100
165/165 - 1s - loss: 0.0021 - mse: 0.0021 - val_loss: 0.0084 - val_mse: 0.0084 - 1s/epoch - 8ms/step
Epoch 8/100
165/165 - 1s - loss: 0.0023 - mse: 0.0023 - val_loss: 0.0085 - val_mse: 0.0085 - 1s/epoch - 8ms/step
Epoch 9/100
165/165 - 1s - loss: 0.0024 - mse: 0.0024 - val

In [17]:
import pickle
i=0
for m in models:
    test_x2 = test_X
    yhat = m.predict(test_x2)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparams[i])
    print("Epoch: "+ str(lstms[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].units))
    print(Evaluation.mape(inv_y,inv_yhat)[0])
    with open('LSTM_BTC'+str(hyperparams[i])+'.pkl', 'wb') as f:
        pickle.dump(lstms[i].history, f)
    i = i+1

 34/165 [=====>........................] - ETA: 0s

2023-03-21 23:10:42.959732: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:42.984493: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(32, 100, 50)
Epoch: 100
Neurons: 50
2.445515372291245
 36/165 [=====>........................] - ETA: 0s

2023-03-21 23:10:43.632361: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:43.657045: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(32, 100, 60)
Epoch: 100
Neurons: 60
2.1117742994426774
 37/165 [=====>........................] - ETA: 0s

2023-03-21 23:10:44.270537: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:44.294774: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(32, 100, 100)
Epoch: 100
Neurons: 100
2.904281232955527
 33/165 [=====>........................] - ETA: 0s

2023-03-21 23:10:44.893562: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:44.917728: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(64, 100, 50)
Epoch: 100
Neurons: 50
1.4829463631572743
 35/165 [=====>........................] - ETA: 0s

2023-03-21 23:10:45.529409: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:45.553690: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(64, 100, 60)
Epoch: 100
Neurons: 60
1.4775368869605594
 39/165 [======>.......................] - ETA: 0s

2023-03-21 23:10:46.158907: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:46.183205: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 2ms/step
(64, 100, 100)
Epoch: 100
Neurons: 100
2.114705485324059
 38/165 [=====>........................] - ETA: 0s

2023-03-21 23:10:46.764557: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:46.788821: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(128, 100, 50)
Epoch: 100
Neurons: 50
1.6096092686408856
 37/165 [=====>........................] - ETA: 0s

2023-03-21 23:10:47.381922: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:47.406834: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(128, 100, 60)
Epoch: 100
Neurons: 60
1.1495771790529934
 37/165 [=====>........................] - ETA: 0s

2023-03-21 23:10:48.000686: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-21 23:10:48.024976: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


165/165 [==============================] - 1s 3ms/step
(128, 100, 100)
Epoch: 100
Neurons: 100
2.464434639353171


In [18]:
with open('LSTM_BTC(32, 100, 50).pkl', "rb") as file_pi:
    history = pickle.load(file_pi)