In [35]:
from Skripsi import Preprocessing
from Skripsi import Evaluation
from Skripsi import LSTMUnit
from pandas import read_csv
from pandas import DataFrame
import numpy as np
import pandas as pd
from openpyxl.workbook import Workbook
import pickle

In [11]:
btc_dfd = pd.read_csv('Binance_BTCUSDT_1h.csv')
btc_dfd

Unix                 Date   Symbol      Open      High  \
0      1672527600000  2022-12-31 23:00:00  BTCUSDT  16520.28  16551.24   
1      1672524000000  2022-12-31 22:00:00  BTCUSDT  16548.28  16567.49   
2      1672520400000  2022-12-31 21:00:00  BTCUSDT  16568.19  16571.64   
3      1672516800000  2022-12-31 20:00:00  BTCUSDT  16570.14  16574.97   
4      1672513200000  2022-12-31 19:00:00  BTCUSDT  16577.78  16590.06   
...              ...                  ...      ...       ...       ...   
26269  1577851200000  2020-01-01 04:00:00  BTCUSDT   7225.00   7230.00   
26270  1577847600000  2020-01-01 03:00:00  BTCUSDT   7242.66   7245.00   
26271  1577844000000  2020-01-01 02:00:00  BTCUSDT   7215.52   7244.87   
26272  1577840400000  2020-01-01 01:00:00  BTCUSDT   7176.47   7230.00   
26273  1577836800000  2020-01-01 00:00:00  BTCUSDT   7195.24   7196.25   

            Low     Close   Volume BTC   Volume USDT  tradecount  
0      16487.74  16542.40  4973.433070  8.217183e+07      152632  
1      16470.00  16520.81  6695.136250  1.106669e+08      153933  
2      16544.12  16548.28  3618.773890  5.992803e+07      105065  
3      16564.09  16568.60  2622.143550  4.344849e+07       90705  
4      16565.10  16570.14  4044.433590  6.704605e+07      116587  
...         ...       ...          ...           ...         ...  
26269   7215.03   7217.27   467.812578  3.379094e+06        5896  
26270   7220.00   7225.01   783.724867  5.667367e+06        8337  
26271   7211.41   7242.85   655.156809  4.736719e+06        7466  
26272   7175.71   7216.27   883.052603  6.365953e+06        9033  
26273   7175.46   7177.02   511.814901  3.675857e+06        7640  

[26274 rows x 10 columns]

In [12]:
df = Preprocessing.feature_selection(btc_dfd)
df

Open      High       Low   Volume USDT     Close
0       7195.24   7196.25   7175.46  3.675857e+06   7177.02
1       7176.47   7230.00   7175.71  6.365953e+06   7216.27
2       7215.52   7244.87   7211.41  4.736719e+06   7242.85
3       7242.66   7245.00   7220.00  5.667367e+06   7225.01
4       7225.00   7230.00   7215.03  3.379094e+06   7217.27
...         ...       ...       ...           ...       ...
26269  16577.78  16590.06  16565.10  6.704605e+07  16570.14
26270  16570.14  16574.97  16564.09  4.344849e+07  16568.60
26271  16568.19  16571.64  16544.12  5.992803e+07  16548.28
26272  16548.28  16567.49  16470.00  1.106669e+08  16520.81
26273  16520.28  16551.24  16487.74  8.217183e+07  16542.40

[26274 rows x 5 columns]

In [13]:
df_no_dup = Preprocessing.handle_duplicate(df)
df_no_dup

duplicate ok


Open      High       Low   Volume USDT     Close
0       7195.24   7196.25   7175.46  3.675857e+06   7177.02
1       7176.47   7230.00   7175.71  6.365953e+06   7216.27
2       7215.52   7244.87   7211.41  4.736719e+06   7242.85
3       7242.66   7245.00   7220.00  5.667367e+06   7225.01
4       7225.00   7230.00   7215.03  3.379094e+06   7217.27
...         ...       ...       ...           ...       ...
26269  16577.78  16590.06  16565.10  6.704605e+07  16570.14
26270  16570.14  16574.97  16564.09  4.344849e+07  16568.60
26271  16568.19  16571.64  16544.12  5.992803e+07  16548.28
26272  16548.28  16567.49  16470.00  1.106669e+08  16520.81
26273  16520.28  16551.24  16487.74  8.217183e+07  16542.40

[26274 rows x 5 columns]

In [14]:
miss = Preprocessing.handle_missing_value(df_no_dup)
miss

No missing value


False

In [15]:
x, scaler = Preprocessing.minmax_scale(df_no_dup)
x

array([[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
       [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
       [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
       ...,
       [0.19280946, 0.1857686 , 0.19734306, 0.01993857, 0.19251245],
       [0.19250079, 0.18570415, 0.19619691, 0.03681983, 0.19208658],
       [0.19206671, 0.18545178, 0.19647123, 0.02733927, 0.19242129]])

In [16]:
train, test = Preprocessing.splitting_data(x)
train

array([[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
       [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
       [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
       ...,
       [0.39451404, 0.38918512, 0.39751838, 0.01247029, 0.39344233],
       [0.39342821, 0.38742771, 0.39264325, 0.02946575, 0.3886748 ],
       [0.38866059, 0.38484765, 0.39034385, 0.03564371, 0.38670838]])

In [17]:
test

array([[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
       [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
       [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
       ...,
       [0.19280946, 0.1857686 , 0.19734306, 0.01993857, 0.19251245],
       [0.19250079, 0.18570415, 0.19619691, 0.03681983, 0.19208658],
       [0.19206671, 0.18545178, 0.19647123, 0.02733927, 0.19242129]])

In [18]:
train_X, train_y = Preprocessing.create_dataset(train,300)
test_X, test_y = Preprocessing.create_dataset(test,300)

In [19]:
train_X

array([[[0.04750117, 0.0401654 , 0.05247223, 0.00122299, 0.04722846],
        [0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
        [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        ...,
        [0.06200866, 0.0547057 , 0.06655238, 0.00428187, 0.06174979],
        [0.06173953, 0.05465134, 0.06666171, 0.00421005, 0.06193583],
        [0.06192541, 0.0546911 , 0.06638213, 0.00395013, 0.06115013]],

       [[0.04721018, 0.04068955, 0.0524761 , 0.00211801, 0.04783696],
        [0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.04797246],
        ...,
        [0.06173953, 0.05465134, 0.06666171, 0.00421005, 0.06193583],
        [0.06192541, 0.0546911 , 0.06638213, 0.00395013, 0.06115013],
        [0.06116887, 0.05414055, 0.06608663, 0.0049021 , 0.06142671]],

       [[0.04781557, 0.04092048, 0.05302814, 0.00157595, 0.04824904],
        [0.04823632, 0.0409225 , 0.05316097, 0.00188558, 0.0

In [20]:
train_y

array([0.06142671, 0.0613326 , 0.06138252, ..., 0.39344233, 0.3886748 ,
       0.38670838])

In [21]:
test_X

array([[[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
        [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        ...,
        [0.40926788, 0.40262945, 0.41062418, 0.01219459, 0.40699068],
        [0.40697639, 0.40223653, 0.41068465, 0.0162002 , 0.40742585],
        [0.4074114 , 0.40130797, 0.40713256, 0.02645317, 0.40319241]],

       [[0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.38442601],
        ...,
        [0.40697639, 0.40223653, 0.41068465, 0.0162002 , 0.40742585],
        [0.4074114 , 0.40130797, 0.40713256, 0.02645317, 0.40319241],
        [0.40317816, 0.40831915, 0.40620708, 0.06691204, 0.41293939]],

       [[0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.3

In [22]:
test_y

array([0.41293939, 0.40765685, 0.40844782, ..., 0.19251245, 0.19208658,
       0.19242129])

In [23]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(20719, 300, 5) (20719,) (4955, 300, 5) (4955,)


## Model Training

In [24]:
hyperparams = []
batch = [32, 64, 128]
epoch = [25, 50, 100]
neuron = [50, 60, 100]
for j in batch:
    for k in epoch:
        for l in neuron:
            hyperparams.append((j,k,l))
hyperparams

[(32, 25, 50),
 (32, 25, 60),
 (32, 25, 100),
 (32, 50, 50),
 (32, 50, 60),
 (32, 50, 100),
 (32, 100, 50),
 (32, 100, 60),
 (32, 100, 100),
 (64, 25, 50),
 (64, 25, 60),
 (64, 25, 100),
 (64, 50, 50),
 (64, 50, 60),
 (64, 50, 100),
 (64, 100, 50),
 (64, 100, 60),
 (64, 100, 100),
 (128, 25, 50),
 (128, 25, 60),
 (128, 25, 100),
 (128, 50, 50),
 (128, 50, 60),
 (128, 50, 100),
 (128, 100, 50),
 (128, 100, 60),
 (128, 100, 100)]

In [25]:
hyperparam1 = hyperparams[:9]
hyperparam2 = hyperparams[9:18]
hyperparam3 = hyperparams[18:27]
hyperparam1

[(32, 25, 50),
 (32, 25, 60),
 (32, 25, 100),
 (32, 50, 50),
 (32, 50, 60),
 (32, 50, 100),
 (32, 100, 50),
 (32, 100, 60),
 (32, 100, 100)]

In [26]:
hyperparam2

[(64, 25, 50),
 (64, 25, 60),
 (64, 25, 100),
 (64, 50, 50),
 (64, 50, 60),
 (64, 50, 100),
 (64, 100, 50),
 (64, 100, 60),
 (64, 100, 100)]

In [27]:
hyperparam3

[(128, 25, 50),
 (128, 25, 60),
 (128, 25, 100),
 (128, 50, 50),
 (128, 50, 60),
 (128, 50, 100),
 (128, 100, 50),
 (128, 100, 60),
 (128, 100, 100)]

In [28]:
lstms1 = []
models1 = []
for batch, epoch, neuron in hyperparam1:
    model, lstm = LSTMUnit.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms1.append(lstm)
    models1.append(model)

Epoch 1/25
648/648 - 14s - loss: 5.0399e-04 - val_loss: 4.4067e-04 - 14s/epoch - 22ms/step
Epoch 2/25
648/648 - 8s - loss: 5.0131e-04 - val_loss: 3.3815e-04 - 8s/epoch - 12ms/step
Epoch 3/25
648/648 - 6s - loss: 9.1248e-04 - val_loss: 0.0011 - 6s/epoch - 10ms/step
Epoch 4/25
648/648 - 7s - loss: 9.7008e-04 - val_loss: 0.0011 - 7s/epoch - 11ms/step
Epoch 5/25
648/648 - 7s - loss: 7.9657e-04 - val_loss: 7.4044e-04 - 7s/epoch - 11ms/step
Epoch 6/25
648/648 - 7s - loss: 6.5465e-04 - val_loss: 4.7957e-04 - 7s/epoch - 10ms/step
Epoch 7/25
648/648 - 7s - loss: 5.3935e-04 - val_loss: 2.9357e-04 - 7s/epoch - 11ms/step
Epoch 8/25
648/648 - 6s - loss: 4.5137e-04 - val_loss: 1.7201e-04 - 6s/epoch - 10ms/step
Epoch 9/25
648/648 - 7s - loss: 3.8407e-04 - val_loss: 1.0031e-04 - 7s/epoch - 11ms/step
Epoch 10/25
648/648 - 6s - loss: 3.3456e-04 - val_loss: 6.3699e-05 - 6s/epoch - 10ms/step
Epoch 11/25
648/648 - 7s - loss: 2.9765e-04 - val_loss: 4.8016e-05 - 7s/epoch - 11ms/step
Epoch 12/25
648/648 - 7s 

In [44]:
i=0
wb1 = Workbook()
ws1 = wb1.active
for m in models1:
    # make a prediction
    test_x2 = test_X
    yhat = LSTMUnit.predict(test_x2, m)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparam1[i])
    print("Epoch: "+ str(lstms1[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].units))
    i = i+1
    ws1['A'+str(i)] = 'LSTM'
    ws1['B'+str(i)] = hyperparam1[i-1][0]
    ws1['C'+str(i)] = hyperparam1[i-1][1]
    ws1['D'+str(i)] = hyperparam1[i-1][2]
    print('RMSE')
    print(Evaluation.rmse(inv_y,inv_yhat)[0])
    ws1['E'+str(i)] = Evaluation.rmse(inv_y,inv_yhat)[0]
    print('MAE')
    print(Evaluation.mae(inv_y,inv_yhat)[0])
    ws1['F'+str(i)] = Evaluation.mae(inv_y,inv_yhat)[0]
    print('MAPE')
    print(Evaluation.mape(inv_y,inv_yhat)[0])
    ws1['G'+str(i)] = Evaluation.mape(inv_y,inv_yhat)[0]
    LSTMUnit.save_model(m, 0, 'BTC',hyperparam1[i-1])
    with open('LSTM_BTC'+str(hyperparam1[i-1])+'.pkl', 'wb') as f:
        pickle.dump(lstms1[i-1].history, f)
wb1.save('LSTM_BTC_result1.xlsx')

155/155 [==============================] - 1s 5ms/step
(32, 25, 50)
Epoch: 25
Neurons: 50
RMSE
532.1764906174302
MAE
460.3858109627263
MAPE
2.4457676397137926
155/155 [==============================] - 1s 5ms/step
(32, 25, 60)
Epoch: 25
Neurons: 60
RMSE
397.9243391974883
MAE
340.20446466637253
MAPE
1.797008217992619
155/155 [==============================] - 1s 5ms/step
(32, 25, 100)
Epoch: 25
Neurons: 100
RMSE
547.566212962055
MAE
479.6947897877779
MAPE
2.543376340502843
155/155 [==============================] - 1s 7ms/step
(32, 50, 50)
Epoch: 50
Neurons: 50
RMSE
398.3826881682752
MAE
335.60102253090344
MAPE
1.775005545641017
155/155 [==============================] - 1s 5ms/step
(32, 50, 60)
Epoch: 50
Neurons: 60
RMSE
366.1727043014443
MAE
305.33945816252543
MAPE
1.615008160342502
155/155 [==============================] - 1s 5ms/step
(32, 50, 100)
Epoch: 50
Neurons: 100
RMSE
452.40101367783365
MAE
388.66831093119333
MAPE
2.062259704280385
155/155 [==============================] - 

In [30]:
lstms2 = []
models2 = []
for batch, epoch, neuron in hyperparam2:
    model, lstm = LSTMUnit.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms2.append(lstm)
    models2.append(model)

Epoch 1/25
324/324 - 7s - loss: 7.3660e-04 - val_loss: 5.0734e-04 - 7s/epoch - 20ms/step
Epoch 2/25
324/324 - 4s - loss: 5.8289e-04 - val_loss: 2.8279e-04 - 4s/epoch - 11ms/step
Epoch 3/25
324/324 - 4s - loss: 3.9583e-04 - val_loss: 1.9726e-04 - 4s/epoch - 12ms/step
Epoch 4/25
324/324 - 3s - loss: 3.1936e-04 - val_loss: 1.3783e-04 - 3s/epoch - 10ms/step
Epoch 5/25
324/324 - 3s - loss: 2.6125e-04 - val_loss: 9.9110e-05 - 3s/epoch - 11ms/step
Epoch 6/25
324/324 - 4s - loss: 2.1202e-04 - val_loss: 7.8274e-05 - 4s/epoch - 11ms/step
Epoch 7/25
324/324 - 4s - loss: 1.6980e-04 - val_loss: 6.8379e-05 - 4s/epoch - 12ms/step
Epoch 8/25
324/324 - 3s - loss: 1.3651e-04 - val_loss: 5.6751e-05 - 3s/epoch - 11ms/step
Epoch 9/25
324/324 - 3s - loss: 1.1423e-04 - val_loss: 3.7917e-05 - 3s/epoch - 11ms/step
Epoch 10/25
324/324 - 4s - loss: 1.0238e-04 - val_loss: 2.2423e-05 - 4s/epoch - 12ms/step
Epoch 11/25
324/324 - 3s - loss: 9.7060e-05 - val_loss: 1.5221e-05 - 3s/epoch - 11ms/step
Epoch 12/25
324/324

In [45]:
i=0
wb2 = Workbook()
ws2 = wb2.active
for m in models2:
    # make a prediction
    test_x2 = test_X
    yhat = LSTMUnit.predict(test_x2, m)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparam2[i])
    print("Epoch: "+ str(lstms2[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].units))
    i = i+1
    ws2['A'+str(i)] = 'LSTM'
    ws2['B'+str(i)] = hyperparam2[i-1][0]
    ws2['C'+str(i)] = hyperparam2[i-1][1]
    ws2['D'+str(i)] = hyperparam2[i-1][2]
    print('RMSE')
    print(Evaluation.rmse(inv_y,inv_yhat)[0])
    ws2['E'+str(i)] = Evaluation.rmse(inv_y,inv_yhat)[0]
    print('MAE')
    print(Evaluation.mae(inv_y,inv_yhat)[0])
    ws2['F'+str(i)] = Evaluation.mae(inv_y,inv_yhat)[0]
    print('MAPE')
    print(Evaluation.mape(inv_y,inv_yhat)[0])
    ws2['G'+str(i)] = Evaluation.mape(inv_y,inv_yhat)[0]
    LSTMUnit.save_model(m, 0, 'BTC',hyperparam2[i-1])
    with open('LSTM_BTC'+str(hyperparam2[i-1])+'.pkl', 'wb') as f:
        pickle.dump(lstms2[i-1].history, f)
wb2.save('LSTM_BTC_result2.xlsx')

155/155 [==============================] - 1s 5ms/step
(64, 25, 50)
Epoch: 25
Neurons: 50
RMSE
338.1048126842817
MAE
289.2822532716328
MAPE
1.5258787290232854
155/155 [==============================] - 1s 5ms/step
(64, 25, 60)
Epoch: 25
Neurons: 60
RMSE
420.13671396252073
MAE
368.5686361393161
MAPE
1.9532782569907214
155/155 [==============================] - 1s 5ms/step
(64, 25, 100)
Epoch: 25
Neurons: 100
RMSE
2069.9170329218236
MAE
2033.0328820635664
MAPE
10.555456253665367
155/155 [==============================] - 1s 5ms/step
(64, 50, 50)
Epoch: 50
Neurons: 50
RMSE
375.8559766618394
MAE
324.58839203613843
MAPE
1.7256406533054256
155/155 [==============================] - 1s 5ms/step
(64, 50, 60)
Epoch: 50
Neurons: 60
RMSE
365.5820200413883
MAE
320.14965526456956
MAPE
1.695558397829363
155/155 [==============================] - 1s 5ms/step
(64, 50, 100)
Epoch: 50
Neurons: 100
RMSE
338.4736767135669
MAE
300.3025002601548
MAPE
1.5787721318708408
155/155 [=============================

In [32]:
lstms3 = []
models3 = []
for batch, epoch, neuron in hyperparam3:
    model, lstm = LSTMUnit.train_lstm(train_X, train_y, test_X, test_y, neuron, epoch, batch)
    lstms3.append(lstm)
    models3.append(model)

Epoch 1/25
162/162 - 5s - loss: 8.9307e-04 - val_loss: 5.3781e-04 - 5s/epoch - 29ms/step
Epoch 2/25
162/162 - 2s - loss: 8.1998e-04 - val_loss: 0.0021 - 2s/epoch - 12ms/step
Epoch 3/25
162/162 - 2s - loss: 0.0011 - val_loss: 0.0028 - 2s/epoch - 12ms/step
Epoch 4/25
162/162 - 2s - loss: 0.0015 - val_loss: 0.0059 - 2s/epoch - 12ms/step
Epoch 5/25
162/162 - 2s - loss: 0.0017 - val_loss: 0.0073 - 2s/epoch - 12ms/step
Epoch 6/25
162/162 - 2s - loss: 0.0018 - val_loss: 0.0073 - 2s/epoch - 12ms/step
Epoch 7/25
162/162 - 2s - loss: 0.0020 - val_loss: 0.0077 - 2s/epoch - 14ms/step
Epoch 8/25
162/162 - 2s - loss: 0.0024 - val_loss: 0.0066 - 2s/epoch - 12ms/step
Epoch 9/25
162/162 - 2s - loss: 0.0027 - val_loss: 0.0043 - 2s/epoch - 12ms/step
Epoch 10/25
162/162 - 2s - loss: 0.0024 - val_loss: 0.0019 - 2s/epoch - 12ms/step
Epoch 11/25
162/162 - 2s - loss: 0.0019 - val_loss: 4.7627e-04 - 2s/epoch - 12ms/step
Epoch 12/25
162/162 - 2s - loss: 0.0013 - val_loss: 7.3700e-05 - 2s/epoch - 12ms/step
Epoch

In [46]:
i=0
wb3 = Workbook()
ws3 = wb3.active
for m in models3:
    # make a prediction
    test_x2 = test_X
    yhat = LSTMUnit.predict(test_x2, m)
    inv_yhat = Preprocessing.inverse_scaler(yhat, scaler)
    inv_y = Preprocessing.inverse_scaler(test_y.reshape(-1,1), scaler)
    print(hyperparam3[i])
    print("Epoch: "+ str(lstms3[i].params['epochs']))
    print("Neurons: "+str(m.layers[0].units))
    i = i+1
    ws3['A'+str(i)] = 'LSTM'
    ws3['B'+str(i)] = hyperparam3[i-1][0]
    ws3['C'+str(i)] = hyperparam3[i-1][1]
    ws3['D'+str(i)] = hyperparam3[i-1][2]
    print('RMSE')
    print(Evaluation.rmse(inv_y,inv_yhat)[0])
    ws3['E'+str(i)] = Evaluation.rmse(inv_y,inv_yhat)[0]
    print('MAE')
    print(Evaluation.mae(inv_y,inv_yhat)[0])
    ws3['F'+str(i)] = Evaluation.mae(inv_y,inv_yhat)[0]
    print('MAPE')
    print(Evaluation.mape(inv_y,inv_yhat)[0])
    ws3['G'+str(i)] = Evaluation.mape(inv_y,inv_yhat)[0]
    LSTMUnit.save_model(m, 0, 'BTC',hyperparam3[i-1])
    with open('LSTM_BTC'+str(hyperparam3[i-1])+'.pkl', 'wb') as f:
        pickle.dump(lstms3[i-1].history, f)
wb3.save('LSTM_BTC_result3.xlsx')

155/155 [==============================] - 1s 5ms/step
(128, 25, 50)
Epoch: 25
Neurons: 50
RMSE
1811.2581283732268
MAE
1778.463557470355
MAPE
8.972840966212372
155/155 [==============================] - 1s 5ms/step
(128, 25, 60)
Epoch: 25
Neurons: 60
RMSE
1169.9186039499443
MAE
1129.385052961023
MAPE
5.686554642160441
155/155 [==============================] - 1s 4ms/step
(128, 25, 100)
Epoch: 25
Neurons: 100
RMSE
361.6806855294334
MAE
285.1503571833999
MAPE
1.478515286406289
155/155 [==============================] - 1s 5ms/step
(128, 50, 50)
Epoch: 50
Neurons: 50
RMSE
506.9025091514095
MAE
369.316171961719
MAPE
1.814055867446476
155/155 [==============================] - 1s 5ms/step
(128, 50, 60)
Epoch: 50
Neurons: 60
RMSE
827.0314353035488
MAE
748.8200228541257
MAPE
3.7205511553573665
155/155 [==============================] - 1s 4ms/step
(128, 50, 100)
Epoch: 50
Neurons: 100
RMSE
1171.0644693190106
MAE
1130.3485636273317
MAPE
5.6962808993075615
155/155 [============================

In [34]:
test_X

array([[[0.38669404, 0.3808301 , 0.38809703, 0.0406164 , 0.38493033],
        [0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        ...,
        [0.40926788, 0.40262945, 0.41062418, 0.01219459, 0.40699068],
        [0.40697639, 0.40223653, 0.41068465, 0.0162002 , 0.40742585],
        [0.4074114 , 0.40130797, 0.40713256, 0.02645317, 0.40319241]],

       [[0.38491617, 0.38016586, 0.38748453, 0.03251634, 0.38538193],
        [0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.38442601],
        ...,
        [0.40697639, 0.40223653, 0.41068465, 0.0162002 , 0.40742585],
        [0.4074114 , 0.40130797, 0.40713256, 0.02645317, 0.40319241],
        [0.40317816, 0.40831915, 0.40620708, 0.06691204, 0.41293939]],

       [[0.38536761, 0.38119677, 0.38950296, 0.01847402, 0.38586346],
        [0.38584929, 0.38055428, 0.38798971, 0.02809654, 0.3